### ISSUE TITLE
[Feature Request] Notches in Boxplots

### ISSUE THREAD

**Issue by iandol** [piermorel/gramm#10]
It would be very useful to be able to generate notches on gramm's boxplots. The MATLAB code to generate notches start around #2284 of MATLAB's stats/boxplot.m — though the drawing is done in stats/private/boxrenderer.m @drawLineBoxNotched

**Comment by piermorel** [comment]
Thanks for the suggestion! By the way, all of gramm's boxplot functionality, computing and drawing, is in @gramm/stat_boxplot.m (less than 100 lines in total, including comments), it should be quite easy to modify if you want to try.

**Comment by iandol** [comment]
Yeah, on my TODO list, which unfortunately is very long... ;-)

**Comment by piermorel** [comment]
Took care of it :)
[Example at bottom](https://raw.githubusercontent.com/piermorel/gramm/master/html/examples_15.png)

**Comment by iandol** [comment]
@piermorel 👍 😎
