### ISSUE TITLE
Correlation plot with different markers but one fit line

### ISSUE THREAD

**Issue by wildetudor** [piermorel/gramm#102]
Hi Pier,

Is it possible to create a correlation (scatter) plot with differently-coloured markers, but for the GLM fit line to not be drawn separately for each group, but for the entire sample?

With the following code, I tried to create a single stat_glm object, but later updating to draw the markers differently according to group membership:

```
x = randn(1,10);
y = randn(1,10);
groupMembership = ['M' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'F' 'F' ];
g = gramm('x',x,  'y',y); 
g.geom_point(); 
g.stat_glm(); 
g.draw();

g.update('x',x,  'y',y,  'color', groupMembership);
g.set_names('color', groupMembership)
g.geom_point();
g.draw();
```

Instead, what I get by playing around with the code in various ways, is either two fit lines, or one fit line but with no difference in marker colors.

Can you help? Many thanks!

**Comment by piermorel** [comment]
Hi, there is code for doing just that in examples.m (from line 860 on). I guess your mistake is that you respecified x and y, with update you should just add what changed !
