### ISSUE TITLE
How to set the order of facet_grid sub-panels. 

### ISSUE THREAD

**Issue by jingweimo** [piermorel/gramm#105]
The default order seems to be in the alphabetic order for the sub-panels.  The set_order_options only allows change the order by 'x' and 'color' not by the sub-panels.  I wonder how to define custom order in which the sub panels are drawn.

**Comment by piermorel** [comment]
Hi @jingweimo 
Sorry for the gigantic wait. Gramm was on hold but I now have the opportunity to work on it! You can use `'column'` and `'row'`arguments in `set_order_options()`to do changes on subpanel order.
