### ISSUE TITLE
color part of the background

### ISSUE THREAD

**Issue by danielemarinazzo** [piermorel/gramm#107]
Hi

is there a way to color part of the background, using the equivalent of `area` or `patch`?

e.g.

```
figure;scatter(rand(100,1),rand(100,1))
vert = [0 0;1 1;0 1]; % x and y vertex coordinates
patch('Faces',fac,'Vertices',vert,'FaceAlpha',.5,'FaceColor','g');
vert = [0 0;1 1;1 0]; % x and y vertex coordinates
patch('Faces',fac,'Vertices',vert,'FaceAlpha',.5,'FaceColor','r');
```

thanks!

**Comment by piermorel** [comment]
Hi @danielemarinazzo 
Sorry for the gigantic wait. Gramm was on hold but I now have the opportunity to work on it! You should be able to use the method `geom_polygon()`to do just that ! There is a example in examples.m in the section "Decorate plot backgrounds with geom_polygon()"
