### ISSUE TITLE
Barplot in logarithmic x-axis

### ISSUE THREAD

**Issue by Niklas123Niklas** [piermorel/gramm#108]
Hello,
thanks for this nice adaption of graphics grammar to matlab. While I created a boxplot on a logarithmnic x-axis, the width of the boxes seems to be fixed for a specific value. This does not work for logarithmic axis. The width is changing from very wide boxes to thin lines over 2 decades. Is it possible to fix this behaviour for log axes?

Cheers
Niklas

Try the following code:

    %Create data
    x=repmat(1:10,1,100);
    catx=repmat([1 2 4 8 16 32 64 128 256 512]*0.01,1,100);
    y=randn(1,1000)*3;
    y=2+y+x+c*0.5;
    %Draw
    clear g
    figure()
    g=gramm('x',catx,'y',y);
    g.stat_boxplot();
    g.axe_property("XScale","log");
    g.set_title('Width of Boxplot changes from thick to thin');
    g.draw();

**Comment by piermorel** [comment]
Hi @Niklas123Niklas 
Thank you for the issue, and sorry for the gigantic wait. Gramm was on hold but I now have the opportunity to work on it!
From what I see, Matlab's own boxplot doesn't behave properly when axes are logarithmic. In these case I would suggest to "fake it" by making x a categorical variable and/or modifying the ticks/legends without actually setting the axis to log.
`g=gramm('x',categorical(catx),'y',y);
g.stat_boxplot();
g.set_title('Width of Boxplot changes from thick to thin');
g.draw();`
After the draw call it's possible to edit the x ticks (or before with `axe_property`) to get values that match what you want.

**Comment by Niklas123Niklas** [comment]
Hi @piermorel,
thanks for the comment. I looked into what I was asking for, and replacing the labels made me think of just using log10(x) to convert the data in logartihmic values, plot them on linear scale and adjust the labels to powers of 10. With this, the width of the bars is nice and the label adjustments would be similar as your suggestion.
   
```matlab
%Create data
x=repmat(1:10,1,100);
catx=repmat([1 2 4 8 16 32 64 128 256 512]*0.01,1,100);
y=randn(1,1000)*3;
y=2+y+x+catx*0.5;
%Draw
clear g
figure()
g=gramm('x',log10(catx),'y',y); % log10 here
g.stat_boxplot();
g.set_title('Width of Boxplot changes from thick to thin');
g.draw();
```
