### ISSUE TITLE
Standard deviation on mean plots

### ISSUE THREAD

**Issue by z-aftab** [piermorel/gramm#110]
Awesome submission.
I was just wondering if there is a way to show Mean +- Std Dev. in "stat_summary" method? Apparently the available options plot 95% CI which is not the same. Often we need to plot error bars using Std. Dev.

**Comment by bergem1t** [comment]
`stat_summary` has a parameter called "type" that lets you choose the error type.
`stat_summary('type','std')` will do Std. Dev. 
Other types are possible such as S.E.M. and also custom error functions.
Check out the documentation: `doc stat_summary`. You will see all options.

**Comment by tomjensen2** [comment]
Excellent analysis/plotting tool. Thank you for your work. One question, is it possible to specify the figure target for a draw call? 

I would hope to use gramm on data output from an app designer GUI, ideally within the gui itself, or using additional figure window. Thanks again.

**Comment by z-aftab** [comment]
Thanks. Actually I was not writing the command in correct order/format. Here is what worked for me eventually as you suggested:
myobject.stat_summary('type','std','geom',{'bar','black_errorbar'});
