### ISSUE TITLE
g.draw() results in crash (Matlab 2021b)

### ISSUE THREAD

**Issue by UserQuaark** [piermorel/gramm#116]
With the new Matlab release, g.draw() crashes the hole program:

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown hardware 
  Graphics Text Issue Info : xmin=-55.499998, ymin=-9.000000, xmax=55.499998, ymax=9.000000
  Graphics card 1          : NVIDIA ( 0x10de ) NVIDIA Quadro P500 Version 27.21.14.5266 (2020-11-20)
  Graphics card 2          : Intel Corporation ( 0x8086 ) Intel(R) UHD Graphics 620 Version 27.20.100.8337 (2020-6-16)
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 8786298
  MATLAB Root              : C:\Program Files\MATLAB\R2021b
  MATLAB Version           : 9.11.0.1769968 (R2021b)
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 10 Enterprise
  Process ID               : 10880
  Processor ID             : x86 Family 6 Model 142 Stepping 10, GenuineIntel
  Session Key              : aad5d69f-c173-4fb7-84cc-a5f379962b69
  Window System            : Version 10.0 (Build 19042)

Fault Count: 1

Abnormal termination:
Access violation

Current Thread: 'MCR 0 interpreter thread' id 2340

Register State (from fault):
  RAX = 0900007ffc70983b  RBX = 00000152f3a738e0
  RCX = 00000152e27a8f20  RDX = 00000152bfe547a0
  RSP = 00000025d24f65c0  RBP = 0000000000000000
  RSI = 0000000000000001  RDI = 00000152bfd50884
 
   R8 = 00000025d24f6620   R9 = 00000025d24f6610
  R10 = 0000000000008000  R11 = 00000025d24f65b0
  R12 = 0000000000000000  R13 = 00000152f46ec218
  R14 = 0000000000000000  R15 = 00000025d24f6a80
 
  RIP = 00007ffc549ccf83  EFL = 00010206
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x00007ffc549ccf83 C:\Program Files\MATLAB\R2021b\bin\win64\libuij.dll+00184195 UIJ_AreThereWindowsBeingPainted+00000051
[  1] 0x00007ffc549d1b0f C:\Program Files\MATLAB\R2021b\bin\win64\libuij.dll+00203535 UIJ_getWaitForResize+00014623
[  2] 0x00007ffc549d89bf C:\Program Files\MATLAB\R2021b\bin\win64\libuij.dll+00231871 UIJ_RegisterDrawnowHooks+00004159
[  3] 0x00007ffc835fb9d7 C:\Program Files\MATLAB\R2021b\bin\win64\libmwservices.dll+02537943 sysq::addProcessPendingEventsUnitTestHook+00001431
[  4] 0x00007ffc835fcc10 C:\Program Files\MATLAB\R2021b\bin\win64\libmwservices.dll+02542608 sysq::addProcessPendingEventsUnitTestHook+00006096
[  5] 0x00007ffc835fda18 C:\Program Files\MATLAB\R2021b\bin\win64\libmwservices.dll+02546200 svWS_ProcessPendingEvents+00000200
[  6] 0x00007ffc726dcf93 C:\Program Files\MATLAB\R2021b\bin\win64\libmwdrawnow.dll+00249747 graphics::drawnow+00000355
[  7] 0x00007ffc726dcf50 C:\Program Files\MATLAB\R2021b\bin\win64\libmwdrawnow.dll+00249680 graphics::drawnow+00000288
[  8] 0x00007ffc726a6dc9 C:\Program Files\MATLAB\R2021b\bin\win64\libmwdrawnow.dll+00028105 hgDrawnow+00000633
[  9] 0x00007ffc7cfc653b C:\Program Files\MATLAB\R2021b\bin\win64\builtin.dll+00091451 MathWorks::builtin::BuiltinFcn::invoke+00000587
[ 10] 0x00007ffc81011fb9                     bin\win64\pgo\m_dispatcher.dll+00073657 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00001449
[ 11] 0x00007ffc81011ec5                     bin\win64\pgo\m_dispatcher.dll+00073413 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00001205
[ 12] 0x00007ffc81011688                     bin\win64\pgo\m_dispatcher.dll+00071304 Mfh_MATLAB_fn_impl::dispatch+00000712
[ 13] 0x00007ffc810113ed                     bin\win64\pgo\m_dispatcher.dll+00070637 Mfh_MATLAB_fn_impl::dispatch+00000045
[ 14] 0x00007ffc7e40ab04                                bin\win64\m_lxe.dll+08563460 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00149940
[ 15] 0x00007ffc7e41811e                                bin\win64\m_lxe.dll+08618270 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00204750
[ 16] 0x00007ffc7e51156e                                bin\win64\m_lxe.dll+09639278 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01225758
[ 17] 0x00007ffc7e512a89                                bin\win64\m_lxe.dll+09644681 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01231161
[ 18] 0x00007ffc7e46d2f8                                bin\win64\m_lxe.dll+08966904 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00553384
[ 19] 0x00007ffc7e4841e9                                bin\win64\m_lxe.dll+09060841 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00647321
[ 20] 0x00007ffc7de59bcb                                bin\win64\m_lxe.dll+02595787 MathWorks::lxe::FeatureLxeTrace+02216811
[ 21] 0x00007ffc7de5df2a                                bin\win64\m_lxe.dll+02613034 MathWorks::lxe::FeatureLxeTrace+02234058
[ 22] 0x00007ffc7de5b4f3                                bin\win64\m_lxe.dll+02602227 MathWorks::lxe::FeatureLxeTrace+02223251
[ 23] 0x00007ffc7de4f615                                bin\win64\m_lxe.dll+02553365 MathWorks::lxe::FeatureLxeTrace+02174389
[ 24] 0x00007ffc7de4f8b0                                bin\win64\m_lxe.dll+02554032 MathWorks::lxe::FeatureLxeTrace+02175056
[ 25] 0x00007ffc7de5ecc6                                bin\win64\m_lxe.dll+02616518 MathWorks::lxe::FeatureLxeTrace+02237542
[ 26] 0x00007ffc7de5ad56                                bin\win64\m_lxe.dll+02600278 MathWorks::lxe::FeatureLxeTrace+02221302
[ 27] 0x00007ffc7df2416d                                bin\win64\m_lxe.dll+03424621 MathWorks::lxe::FeatureLxeTrace+03045645
[ 28] 0x00007ffc7df27ea8                                bin\win64\m_lxe.dll+03440296 MathWorks::lxe::FeatureLxeTrace+03061320
[ 29] 0x00007ffc7e35d411                                bin\win64\m_lxe.dll+07853073 MathWorks::lxe::profiler::MexFunctionCall::EnterPoint+00371889
[ 30] 0x00007ffc7e52ea35                                bin\win64\m_lxe.dll+09759285 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01345765
[ 31] 0x00007ffc7e53e52f                                bin\win64\m_lxe.dll+09823535 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01410015
[ 32] 0x00007ffc7e53e27c                                bin\win64\m_lxe.dll+09822844 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01409324
[ 33] 0x00007ffc70606336                        bin\win64\pgo\mcos_impl.dll+00287542
[ 34] 0x00007ffc70606113                        bin\win64\pgo\mcos_impl.dll+00286995
[ 35] 0x00007ffc70605fbf                        bin\win64\pgo\mcos_impl.dll+00286655
[ 36] 0x00007ffc70612fef                        bin\win64\pgo\mcos_impl.dll+00339951 mdIsA+00022919
[ 37] 0x00007ffc51bcc59e C:\Program Files\MATLAB\R2021b\bin\win64\structuredoutput.dll+00378270 structuredoutput::liveEvaluateExport+00012350
[ 38] 0x00007ffc51bcc1de C:\Program Files\MATLAB\R2021b\bin\win64\structuredoutput.dll+00377310 structuredoutput::liveEvaluateExport+00011390
[ 39] 0x00007ffc51b87c4b C:\Program Files\MATLAB\R2021b\bin\win64\structuredoutput.dll+00097355 structuredoutput::invokeErrorRecoveryHelper+00008907
[ 40] 0x00007ffc51bcbf32 C:\Program Files\MATLAB\R2021b\bin\win64\structuredoutput.dll+00376626 structuredoutput::liveEvaluateExport+00010706
[ 41] 0x00007ffc51bce568 C:\Program Files\MATLAB\R2021b\bin\win64\structuredoutput.dll+00386408 structuredoutput::liveEvaluateExport+00020488
[ 42] 0x00007ffc7061a15e                        bin\win64\pgo\mcos_impl.dll+00368990 mdIsA+00051958
[ 43] 0x00007ffc706196f5                        bin\win64\pgo\mcos_impl.dll+00366325 mdIsA+00049293
[ 44] 0x00007ffc70619390                        bin\win64\pgo\mcos_impl.dll+00365456 mdIsA+00048424
[ 45] 0x00007ffc70652b2f                        bin\win64\pgo\mcos_impl.dll+00600879 mdMethodListAllFcn+00021991
[ 46] 0x00007ffc708101b4                        bin\win64\pgo\mcos_impl.dll+02425268 mwboost::serialization::singleton_module::unlock+01187940
[ 47] 0x00007ffc70877de8                        bin\win64\pgo\mcos_impl.dll+02850280 namedArgsToCell+00004592
[ 48] 0x00007ffc70884ca1                        bin\win64\pgo\mcos_impl.dll+02903201 namedArgsToCell+00057513
[ 49] 0x00007ffcb8e21d38                                 bin\win64\mcos.dll+00138552 omDirectCallMethod+00000072
[ 50] 0x00007ffc7b35f34b                 bin\win64\pgo\libmwlxeindexing.dll+00455499 MathWorks::lxe::MatrixModuleImplementation::SetHeterogeneousArray+00010507
[ 51] 0x00007ffc7b3ef003                 bin\win64\pgo\libmwlxeindexing.dll+01044483 MathWorks::lxe::intermediate_paren_ref_place+00006111
[ 52] 0x00007ffc7b2fe1c3                 bin\win64\pgo\libmwlxeindexing.dll+00057795 MathWorks::lxe::assign_brace_xlist_pointer_uninitialized+00000579
[ 53] 0x00007ffc7b2fe1c3                 bin\win64\pgo\libmwlxeindexing.dll+00057795 MathWorks::lxe::assign_brace_xlist_pointer_uninitialized+00000579
[ 54] 0x00007ffc7b380f92                 bin\win64\pgo\libmwlxeindexing.dll+00593810 MathWorks::lxe::DereferenceRplaceToXvalueZeroOutputs+00000026
[ 55] 0x00007ffc7b34c7d3                 bin\win64\pgo\libmwlxeindexing.dll+00378835 MathWorks::lxe::at_rparen0+00000391
[ 56] 0x00007ffc7e46d2f8                                bin\win64\m_lxe.dll+08966904 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00553384
[ 57] 0x00007ffc7e48ae59                                bin\win64\m_lxe.dll+09088601 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00675081
[ 58] 0x00007ffc7df381e7                                bin\win64\m_lxe.dll+03506663 MathWorks::lxe::FeatureLxeTrace+03127687
[ 59] 0x00007ffc7df23808                                bin\win64\m_lxe.dll+03422216 MathWorks::lxe::FeatureLxeTrace+03043240
[ 60] 0x00007ffc7df27ea8                                bin\win64\m_lxe.dll+03440296 MathWorks::lxe::FeatureLxeTrace+03061320
[ 61] 0x00007ffc7e35d411                                bin\win64\m_lxe.dll+07853073 MathWorks::lxe::profiler::MexFunctionCall::EnterPoint+00371889
[ 62] 0x00007ffc7e4039c6                                bin\win64\m_lxe.dll+08534470 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00120950
[ 63] 0x00007ffc7e40368d                                bin\win64\m_lxe.dll+08533645 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00120125
[ 64] 0x00007ffc7e406232                                bin\win64\m_lxe.dll+08544818 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+00131298
[ 65] 0x00007ffc81012ac0                     bin\win64\pgo\m_dispatcher.dll+00076480 mdWhichInfo::find+00000780
[ 66] 0x00007ffc81013fc1                     bin\win64\pgo\m_dispatcher.dll+00081857 Mfh_file::dispatch+00000045
[ 67] 0x00007ffc7061dc96                        bin\win64\pgo\mcos_impl.dll+00384150 mdIsA+00067118
[ 68] 0x00007ffc70621fb4                        bin\win64\pgo\mcos_impl.dll+00401332 mdIsA+00084300
[ 69] 0x00007ffc7061992d                        bin\win64\pgo\mcos_impl.dll+00366893 mdIsA+00049861
[ 70] 0x00007ffc70619390                        bin\win64\pgo\mcos_impl.dll+00365456 mdIsA+00048424
[ 71] 0x00007ffc7066283f                        bin\win64\pgo\mcos_impl.dll+00665663 mdMethodListAllFcn+00086775
[ 72] 0x00007ffc70662754                        bin\win64\pgo\mcos_impl.dll+00665428 mdMethodListAllFcn+00086540
[ 73] 0x00007ffc7066263a                        bin\win64\pgo\mcos_impl.dll+00665146 mdMethodListAllFcn+00086258
[ 74] 0x00007ffc70604d81                        bin\win64\pgo\mcos_impl.dll+00281985
[ 75] 0x00007ffc810123e0                     bin\win64\pgo\m_dispatcher.dll+00074720 Mfh_MATLAB_fn_impl::ensure_loading_of_load_module+00000672
[ 76] 0x00007ffc81012569                     bin\win64\pgo\m_dispatcher.dll+00075113 Mfh_MATLAB_fn_impl::dispatch_with_reuse+00000045
[ 77] 0x00007ffc7e53a79e                                bin\win64\m_lxe.dll+09807774 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01394254
[ 78] 0x00007ffc7e327c4d                                bin\win64\m_lxe.dll+07633997 MathWorks::lxe::profiler::MexFunctionCall::EnterPoint+00152813
[ 79] 0x00007ffc7e38eecf                                bin\win64\m_lxe.dll+08056527 MathWorks::lxe::profiler::IMexProfilingSupport::~IMexProfilingSupport+00073839
[ 80] 0x00007ffc51bb342d C:\Program Files\MATLAB\R2021b\bin\win64\structuredoutput.dll+00275501 executionPortal+00000173
[ 81] 0x00007ffc7cfc653b C:\Program Files\MATLAB\R2021b\bin\win64\builtin.dll+00091451 MathWorks::builtin::BuiltinFcn::invoke+00000587
[ 82] 0x00007ffc81011fb9                     bin\win64\pgo\m_dispatcher.dll+00073657 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00001449
[ 83] 0x00007ffc81011ec5                     bin\win64\pgo\m_dispatcher.dll+00073413 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00001205
[ 84] 0x00007ffc81010a29                     bin\win64\pgo\m_dispatcher.dll+00068137 mdWhichInfo::fill_hidden_and_non_contextual+00002521
[ 85] 0x00007ffc81010041                     bin\win64\pgo\m_dispatcher.dll+00065601 Mfh_MATLAB_fn_impl::dispatch+00000045
[ 86] 0x00007ffc705fa6be                        bin\win64\pgo\mcos_impl.dll+00239294
[ 87] 0x00007ffc81016b48                     bin\win64\pgo\m_dispatcher.dll+00093000 mdBuiltinAsBuiltinFcn+00000240
[ 88] 0x00007ffc7cfc653b C:\Program Files\MATLAB\R2021b\bin\win64\builtin.dll+00091451 MathWorks::builtin::BuiltinFcn::invoke+00000587
[ 89] 0x00007ffc81011fb9                     bin\win64\pgo\m_dispatcher.dll+00073657 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00001449
[ 90] 0x00007ffc81011ec5                     bin\win64\pgo\m_dispatcher.dll+00073413 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00001205
[ 91] 0x00007ffc810123e0                     bin\win64\pgo\m_dispatcher.dll+00074720 Mfh_MATLAB_fn_impl::ensure_loading_of_load_module+00000672
[ 92] 0x00007ffc81012569                     bin\win64\pgo\m_dispatcher.dll+00075113 Mfh_MATLAB_fn_impl::dispatch_with_reuse+00000045
[ 93] 0x00007ffc7e53a79e                                bin\win64\m_lxe.dll+09807774 mwboost::archive::detail::pointer_oserializer<mwboost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree>::save_object_ptr+01394254
[ 94] 0x00007ffc7e327c4d                                bin\win64\m_lxe.dll+07633997 MathWorks::lxe::profiler::MexFunctionCall::EnterPoint+00152813
[ 95] 0x00007ffc7e327d61                                bin\win64\m_lxe.dll+07634273 MathWorks::lxe::profiler::MexFunctionCall::EnterPoint+00153089
[ 96] 0x00007ffc7e38ef81                                bin\win64\m_lxe.dll+08056705 MathWorks::lxe::profiler::IMexProfilingSupport::~IMexProfilingSupport+00074017
[ 97] 0x00007ffc7e38ea7f                                bin\win64\m_lxe.dll+08055423 MathWorks::lxe::profiler::IMexProfilingSupport::~IMexProfilingSupport+00072735
[ 98] 0x00007ffc7e38f326                                bin\win64\m_lxe.dll+08057638 MathWorks::lxe::profiler::IMexProfilingSupport::~IMexProfilingSupport+00074950
[ 99] 0x00007ffc80de5f0e                    bin\win64\pgo\m_interpreter.dll+00089870 inCallFcnWithTrapInDesiredWSAndPublishEvents+00000098
[100] 0x00007ffc8135a1e2   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00696802 iqm::BaseFEvalPlugin::inCallFcnWithTrap+00000066
[101] 0x00007ffc81359a97   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00694935 iqm::BaseFEvalPlugin::execute+00000455
[102] 0x00007ffc813598b2   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00694450 iqm::FEvalPlugin<cmddistributor::FEvalIIP>::execute+00000018
[103] 0x00007ffc81195dcd   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00482765 services::lmgr::exception::LicensingStartupException::~LicensingStartupException+00008765
[104] 0x00007ffc81342eb2   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00601778 iqm::Iqm::setupIqmFcnPtrs+00094530
[105] 0x00007ffc81316301   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00418561 iqm::Iqm::create+00007281
[106] 0x00007ffc80b93ae5 C:\Program Files\MATLAB\R2021b\bin\win64\libmwbridge.dll+00080613 ioReadLine+00000501
[107] 0x00007ffc80b938b5 C:\Program Files\MATLAB\R2021b\bin\win64\libmwbridge.dll+00080053 ioReadLine+00000165
[108] 0x00007ffc80ba4c50 C:\Program Files\MATLAB\R2021b\bin\win64\libmwbridge.dll+00150608 mnGetCommandLineBuffer+00000288
[109] 0x00007ffc80ba50e2 C:\Program Files\MATLAB\R2021b\bin\win64\libmwbridge.dll+00151778 mnParser+00000466
[110] 0x00007ffc8119b196   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00504214 mcr_set_enableReadingFromStdin+00011862
[111] 0x00007ffc8113f173   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00127347 mcrFunctionSignature::set_signature+00106307
[112] 0x00007ffc8115aec0   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00241344 mcrFunctionSignature::set_signature+00220304
[113] 0x00007ffc8136d1ca   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00774602 iqm::PackagedTaskPlugin::execute+00000074
[114] 0x00007ffc8119609d   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00483485 services::lmgr::exception::LicensingStartupException::~LicensingStartupException+00009485
[115] 0x00007ffc81342eb2   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00601778 iqm::Iqm::setupIqmFcnPtrs+00094530
[116] 0x00007ffc81317646   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00423494 iqm::Iqm::create+00012214
[117] 0x00007ffc81316d32   C:\Program Files\MATLAB\R2021b\bin\win64\iqm.dll+00421170 iqm::Iqm::create+00009890
[118] 0x00007ffc8117463c   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00345660 mcrInstantiationError::operator=+00010444
[119] 0x00007ffc81175095   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00348309 mcrInstantiationError::operator=+00013093
[120] 0x00007ffc81172810   C:\Program Files\MATLAB\R2021b\bin\win64\mcr.dll+00337936 mcrInstantiationError::operator=+00002720
[121] 0x00007ffcd3879baa C:\Program Files\MATLAB\R2021b\bin\win64\mwboost_thread-vc142-mt-x64-1_72.dll+00039850 mwboost::thread::swap+00000074
[122] 0x00007ffcdde81bb2                   C:\Windows\System32\ucrtbase.dll+00138162 configthreadlocale+00000146
[123] 0x00007ffcde9f7034                   C:\Windows\System32\KERNEL32.DLL+00094260 BaseThreadInitThunk+00000020
[124] 0x00007ffce04c2651                      C:\Windows\SYSTEM32\ntdll.dll+00337489 RtlUserThreadStart+00000033

**Comment by piermorel** [comment]
Hello @UserQuaark, I do not have 21b yet to test it, does this crash happen any time draw() is called or only under certain conditions ? Do the examples in examples.m crash as well ?

**Comment by UserQuaark** [comment]
Hello @piermorel , it seems to be a problem of 21b directly. I could reproduce the error when trying to open a figure in an external window in the live editor. It seems that get(gcf, "Visibility", true) is not an workaround for this any more.

**Comment by piermorel** [comment]
Hi @UserQuaark, just to let you know, Mathworks is aware of the issue and it will likely get fixed in a coming Matlab update
