### ISSUE TITLE
ERROR_set_names

### ISSUE THREAD

**Issue by ThirdTiger** [piermorel/gramm#119]
Hi,

When I want to run the example file provided for gramm I get the below error:

Error using gramm/set_names
Method 'set_names' is not defined for class 'gramm' or is removed from MATLAB's search path.

Error in gramm (line 182)
set_names(obj);

Any thought to solve it?

I use MATLAB 9.5.0.944444 (R2018b).

**Comment by piermorel** [comment]
You likely have a path problem, the examples.m files is designed to run from within the gramm folder (the one that **contains** the `@gramm` folder and the examples.m file). Same thing, the folder that needs to be added to your file is the one containing the `@gramm` folder
