### ISSUE TITLE
iscategorical function is undefined

### ISSUE THREAD

**Issue by waldolavado** [piermorel/gramm#12]
I have his bug:
Undefined function 'iscategorical' for input arguments of type
'double'.
Error in validate_aes (line 49)
        if iscategorical(aes.(fields{k}))
Error in gramm/draw (line 80)
obj.aes=validate_aes(obj.aes); 
I'm using Matlab R2013a
Regards

**Comment by piermorel** [comment]
Bad luck, iscategorical() was added to Matlab in 2013b! http://mathworks.com/help/matlab/ref/iscategorical.html

Can you update to a more recent version ? If not, while I add a version test, you can create an iscategorical() function in your path that takes one argument and always returns false.

**Comment by piermorel** [comment]
Should be corrected in the latest commit.
