### ISSUE TITLE
How to make all the subplot in one figure appear in different colours

### ISSUE THREAD

**Issue by suiqianzc** [piermorel/gramm#121]
Hi,

Firstly, it is an amazing tool that I am currently using. But I encountered some issues and hope you can help. I am so curious how to make subplot in one figure appear in different colours based on your tool. For example, if there are 6 bar charts in one figure, I want each bar chart to have a different colour, how do I go about achieving it?

Thank you in advance

**Comment by piermorel** [comment]
Hi, thanks for your feedback ! The easiest way would be to use the same variable that you provided to facet_grid() for the 'color' argument in your initial gramm call.
