### ISSUE TITLE
adding the gramm to the matlab path

### ISSUE THREAD

**Issue by engahmelkholy** [piermorel/gramm#123]
when i try to add this great tool to use it in every matlab project. the matlab refuse to do it 
 addpath 'C:\Users\ahm_e\Documents\MATLAB\gramm\@gramm'
Warning: Method directories not allowed in MATLAB path:
C:\Users\ahm_e\Documents\MATLAB\gramm\@gramm 
> In path (line 109)
In addpath (line 86)

**Comment by piermorel** [comment]
Installation instructions are on the github page (don't use the @gramm in the path)
