### ISSUE TITLE
Draw function overrides figure visibility

### ISSUE THREAD

**Issue by Aditya-Singhvi** [piermorel/gramm#126]
Hi, 

I'm encountering a problem where the draw function automatically makes my figures visible, even as I declared them with the 'visible' option set to 'off'. For reference, I am working with Matlab R2019B. Using the debugger, I concluded that Line 79 is where the figure becomes visible; however, I'm not sure how to fix it. 

Let me know if anyone has a solution to this! It's quite inconvenient to have figures constantly popping up when I'm running analyses in the background, so I prefer to have them invisible whenever possible. 

<img width="884" alt="Screen Shot 2022-06-26 at 17 41 57" src="https://user-images.githubusercontent.com/50927446/175834790-380be063-d9b4-4fa0-9694-8512811afa67.png">

**Comment by piermorel** [comment]
Thank you for the report, and sorry for the wait. Gramm was on hold but I now have the opportunity to work on it and this is fixed.
