### ISSUE TITLE
How to break axis when using gramm package

### ISSUE THREAD

**Issue by CDOM** [piermorel/gramm#128]
Hi all,
Gramm is a great package for figure making in scientific research. However, I didn't find the function which could break the axis. Could any one help me? Thank you.

Best Regards
cdom

**Comment by piermorel** [comment]
Hi @CDOM 
Thanks for the question. There is no built-in way to do that in gramm (and as far as I know it's also the case for Matlab itself). 

However if you don't use `facet_grid()` in your graph I think it's possible to fake it. I added an example called `Create a broken axis` in examples.m

![Capture d’écran 2024-01-17 à 11 35 47](https://github.com/piermorel/gramm/assets/386604/7afa6e9c-b509-4f8a-bbd1-05ebbc8fa737)

**Comment by CDOM** [comment]
Thank you for the nice reply @piermorel
