### ISSUE TITLE
Text properties flexibility

### ISSUE THREAD

**Issue by MooMinIL** [piermorel/gramm#13]
I love this toolbox, it's fantastic and very simple to use, with one exception - in order to change the font size or font name of the axis+legend+titles in my graphs I am forced to write an external function to cycle through all the text objects in the figure which is redundant and messy.
Is there a chance to implement such a functionality in the future?

**Comment by piermorel** [comment]
Hi, I was thinking about adding such functionality... It shouldn't be too hard given that most text handles are stored internally, so stay tuned! Any suggestion on how to handle different font sizes for the different elements (column/row titles are currently a bit smaller than figure titles, etc.) ? I was thinking of having a base font size and then scaling factors for the different elements.

**Comment by MooMinIL** [comment]
My thoughts exactly.
The current font size ratios work great, i believe that they can be scaled to a certain measure.
I would, however, allow the user to change the base font size (which would be the size of, say, the axes labels) and not a scaling factor, this would allow for better integration with other graphs plotted outside of this toolbox.
Another option is to have an extra subroutine for overriding specific font properties for different classes, like "axes labels" or "legend headers" which can be used to override the scaling factor for specific fonts, a sort of 'backdoor' for the user.

**Comment by piermorel** [comment]
Added functionality in the latest commit: base size (ticks) and ratios for everything else can be tweaked, as well as font.
