### ISSUE TITLE
Plot single values together with distributions

### ISSUE THREAD

**Issue by danielemarinazzo** [piermorel/gramm#132]
Hi! Not sure if this is a trivial thing or one already implemented, but is there a straightforward way to plot individual values on top of the distributions? Imagine that I have actual measurements, and then null distributions. Can I display these latter with violin or boxplot, and then have the actual measurements on top?
Thanks!

**Comment by piermorel** [comment]
Hi Daniele,

It's always possible to add both `geom_points()` and `stat_violin()` together if you want both the points and distributions, but I'm not sure that's exactly what you want. 

If you want to plot distributions that are different from the data points, I would suggest looking into `update()` and updating your `y` values (providing the samples from the null first and then updating with your data) ? Let me know if that works for you.
