### ISSUE TITLE
Alternate linestyles

### ISSUE THREAD

**Issue by MooMinIL** [piermorel/gramm#14]
Hey, so I've had another issue, namely with using linestyle for grouping datasets. 
I've got 2 datasets which need to separated by linestyle, but the 2 first default linestyles solid line ('-') and dashed line ('--'), which, under the default legend size, look pretty much the same:
![screen shot 2016-07-20 at 19 43 22](https://cloud.githubusercontent.com/assets/18195169/16994928/404e7e32-4eb2-11e6-8eee-d57c8333c4a5.png)

this is firstly a bug that needs to be taken care of, but more importantly it highlights the fact that the user does not have the freedom to specify the linestyles used at any point, so as to avoid this kind of mix-up.

**Comment by piermorel** [comment]
Ugly dashed lines is almost a matlab bug, but I see what you mean. Until I add an option to set the line style order (I'm away these weeks), you can modify the line:
line_styles={'-' '--' ':' '-.'};
In draw.m

Cheers

**Comment by MooMinIL** [comment]
Awesome, works like a charm!
Thanks for the super fast reply rate BTW!

**Comment by piermorel** [comment]
Now available with set_line_options() along with size preferences.
