### ISSUE TITLE
semi-transparent points

### ISSUE THREAD

**Issue by nbara** [piermorel/gramm#15]
It would be great if geom_point() and geom_jitter() supported alpha, a bit like panel C and D in the attached figure :

![3 copy](https://cloud.githubusercontent.com/assets/10333715/18431041/75e68316-78db-11e6-8521-fd81bd6260d3.jpg)

**Comment by piermorel** [comment]
Unfortunately, points and lines in Matlab do not have any transparency/alpha property (see [Matlab doc](http://www.mathworks.com/help/matlab/ref/chartline-properties.html)), and color can only be given as a RGB triplet for those. So this is rather a request to send to Mathworks than me! I'll see if there are "unofficial" ways to do that though, as it's something that I indeed would like to implement. In the meantime, I just set the transparency in Illustrator (use your vector editing program of choice).

**Comment by piermorel** [comment]
Just found something that should work if mathworks doesn't break it ([Undocumented Matlab](http://undocumentedmatlab.com/blog/plot-markers-transparency-and-color-gradient)). I have to thing about how to best integrated it in gramm:

- As data (ala ggplot2)
- As a color option of set_color_options()
- As a simple option in geom_point() and geom_jitter() (<- I will probably start with that).

**Comment by nbara** [comment]
that would be sweet, thanks!

**Comment by piermorel** [comment]
Added alpha option in the latest commit !
