### ISSUE TITLE
Weird Shading Shape with stat_fit()

### ISSUE THREAD

**Issue by efwb001** [piermorel/gramm#16]
On R2016a (windows, gramm 2.5), I get weird vertical bars of shading (in addition to the correct shading) when I plot a linear regression on 4,000 points using:
figure;
g = gramm('x', x, 'y', y);
g.stat_fit('intopt','observation');
g.draw();

The above code works for:
x=randn(4000,1);
y=x+randn(4000,1)/10; 
However, when I use the data from the below link, the shading contains the (probably) correct margins, plus a vertical bar of shading that extends down to the x axis. The bar moves around between different renderings:
https://github.com/efwb001/random_public_files/blob/master/buggydata.m

**Comment by efwb001** [comment]
K>> opengl info
                          Version: '4.3.0 - Build 10.18.14.4414'
                           Vendor: 'Intel'
                         Renderer: 'Intel(R) HD Graphics 4600'
            RendererDriverVersion: '10.18.14.4414'
        RendererDriverReleaseDate: '23-Mar-2016'
                   MaxTextureSize: 16384
                           Visual: 'Visual 0x07, (RGBA 32 bits (8 8 8 8), Z depth 16 bits, Hardware acceleration, Double buffer, Antialias 8 samples)'
                         Software: 'false'
             HardwareSupportLevel: 'full'
        SupportsGraphicsSmoothing: 1
    SupportsDepthPeelTransparency: 1
       SupportsAlignVertexCenters: 1
                       Extensions: {208x1 cell}
               MaxFrameBufferSize: 16384

**Comment by efwb001** [comment]
![buggyfigure](https://cloud.githubusercontent.com/assets/5223980/19735818/15c37d46-9b7b-11e6-859b-438586c4ce59.png)

**Comment by piermorel** [comment]
Reproduces on Mac 2015b version... very strange bug! From the looks of it it seems that Matlab's fit() function  along with predint() doesn't handle the absence of 'StartPoint' values very well in that case. You do get a warning from Matlab though!

This is solved by providing 'StartPoint' values to stat_fit:
`g = gramm('x', x, 'y', y);`
`g.geom_point('alpha',0.2)`
`g.stat_fit('fun',@(a,b,x)a.*x+b,'StartPoint',[0 0]);`
`g.draw();`

The `'fun',@(a,b,x)a.*x+b` part is not needed as this is the default fitted function. I just put it here to show that there are two parameters a and b and that is why 'StartPoint' is a vector of length 2. The function can be changed!

**Comment by efwb001** [comment]
Thanks piermorel, that's done the trick! I really appreciate the help.
