### ISSUE TITLE
conect data points in paired-samples

### ISSUE THREAD

**Issue by gabrieldelara** [piermorel/gramm#19]
is it possible to conect individual data points from two measures of a dependent variable pair-wise? The study has a repeated measures design. 
One example from R: 

https://gwilymlockwood.wordpress.com/2015/07/15/scatterplot-dotplot-losttheplot/

Thanks.

**Comment by piermorel** [comment]
Hi Gabriel,

This is possible with gramm using update(). The example you give is reproducible apart from the jitter (you could jitter the points but the lines wouldn't connect anymore). Here is some sample code:

```Matlab
%Create fake data
condition=repmat([1 2],1,30);
names={'condition 1' 'condition 2'};
y = randn(1,60);
y(condition == 1) = y(condition ==1) +2;
subject = reshape(repmat(1:30,2,1),60,1);

%First we draw the lines: we need to provide group so that the line is not
%continuous between all points, and we don't provide color so that the
%lines connect the two conditions.
g=gramm('x',names(condition),'y',y,'group',subject);
g.set_color_options('chroma',0); %Make the lines grey instead of the default
g.geom_line();
g.draw();
%Update the data to draw points, by introducing color info and removing group info
g.update('color',names(condition),'group',[]); 
g.set_color_options(); %Reset colors to default
g.geom_point();
g.draw();
```

**Comment by gabrieldelara** [comment]
Hello Mr. Morel,

I thank you immenselly for the help. I am starting to use your toolbox and intend to plot all my data there for my actual two papers and the forthcoming ones.

Congratulations for the effort of creating the toolbox.

Would be nice to include a clear option in the cheatsheat, or commands to do it with jittering (that is what i wanted to do, with jitter).


Thank you again.

Gabriel Amador de Lara

PhD candidate, Clinical neurophysiology

University of Göttingen

________________________________
De: Pierre Morel <notifications@github.com>
Enviado: quinta-feira, 1 de dezembro de 2016 09:34:57
Para: piermorel/gramm
Cc: gabrieldelara; Author
Assunto: Re: [piermorel/gramm] conect data points in paired-samples (#19)


Hi Gabriel,

This is possible with gramm using update(). The example you give is reproducible apart from the jitter (you could jitter the points but the lines wouldn't connect anymore). Here is some sample code:

%Create fake data
condition=repmat([1 2],1,30);
names={'condition 1' 'condition 2'};
y = randn(1,60);
y(condition == 1) = y(condition ==1) +2;
subject = reshape(repmat(1:30,2,1),60,1);

%First we draw the lines: we need to provide group so that the line is not
%continuous between all points, and we don't provide color so that the
%lines connect the two conditions.
g=gramm('x',names(condition),'y',y,'group',subject);
g.set_color_options('chroma',0); %Make the lines grey instead of the default
g.geom_line();
g.draw();
%Update the data to draw points, by introducing color info and removing group info
g.update('color',names(condition),'group',[]);
g.set_color_options(); %Reset colors to default
g.geom_point();
g.draw();

-
