### ISSUE TITLE
Facet & Continuous Colorscale, multiple CLims

### ISSUE THREAD

**Issue by behinger** [piermorel/gramm#2]
If you do facet_grid and have multiple continuous colorscales, they each are mapped on the full scale, instead of their respective domains.

See for example this code:
> figure
> g = gramm('x',repmat(1:10,1,20),'y',1:200,'color',1:200)
> g.geom_line()
> g.facet_grid([repmat({'1'},40,1);repmat({'2'},160,1)],[])
> g.draw

Same thing for facet_wrap.

And here is a screenshot of the output.

![screenshot from 2016-01-29 17 37 36](https://cloud.githubusercontent.com/assets/10183650/12681461/014cd980-c6af-11e5-8ca2-209dfe0d2ccc.png)

**Comment by piermorel** [comment]
Ooops, a line that shouldn't have been commented was.... It's corrected now. I also added a way to set continuous color colormaps, so now your example can be turned to this if you want parula. I also added a 'group' for separating the lines.

```
figure
g = gramm('x',repmat(1:10,1,20),'y',1:200,'color',1:200,'group',reshape(repmat(1:20,10,1),1,200))
g.geom_line()
g.facet_grid([repmat({'1'},40,1);repmat({'2'},160,1)],[])
g.set_continuous_color('colormap','parula')
g.draw
```
