### ISSUE TITLE
Post drawing changes

### ISSUE THREAD

**Issue by MooMinIL** [piermorel/gramm#23]
Hey again!
By now this is my third post on this project, and I have to say that ever since I first started using it over 6 months ago, I have grown more and more dependent on it rather than the normal MATLAB toolkit, so once again - great job with this project. You are doing a service to mankind (or at least the niche that does statistical analysis using MATLAB 😶).

In working this much with this toolbox, I have come to know some of it's limitations - a big one being the inability to make major changes to design after drawing a gramm object.
An example of my current use case - I want to save two versions of a specific graph, one with a title and another with no title.
If this were any normal figure, I would have simply drawn the figure sans title, saved the figure, added a title, then saved the figure again under a different name. In gramm this is much more difficult, as I cannot actually use an existing gramm object to completely redraw and rearrange a figure.
I have also tried copying the gramm object, opening a new figure, and drawing, but I understand now that the gramm object is connected to a specific figure, and cannot be simply copied around.

So I would like to know if you could think up of a workaround for this issue, namely to either be able to completely redraw a figure using an existing gramm object after adding a title and such or to simply copy an existing gramm object into a new one, which can be drawn separately from the original (perhaps this is already implemented but I didn't figure out how to do so?).

In any case, keep up the good work.

**Comment by piermorel** [comment]
Hi, thanks for the kind comment :) I'm well aware that the trade-off for a lot of gramm features is limited customization.

However, doing what you want is completely possible, as gramm objects (at least since the Nov. 1 commit) should be fully copyable at any point. You have to copy them explicitly using copy() though, I use it a lot in the examples.m file.

So in pseudo-gramm code:
```Matlab
g=gramm(...)
g.facet_grid(...)
g.geom_point(...)
%call any gramm method except draw() and update()

gt=copy(g);

figure
g.draw()

gt.set_title(...)
figure
gt.draw()
```

Let me know if that works!

**Comment by MooMinIL** [comment]
Well what do you know!
[http://imgur.com/a/xWEH6](url)
Too bad I already finished this specific keynote, but since it's an automated system that makes the keynote, I'll implement it for the next iteration!
BTW, Maybe the cheatsheet should add some kind of intro section explaining the behavior of gramm objects, specifically these sort of things which might exist in the examples page but aren't necessarily too obvious when browsing through it.

Thanks again for such swift responses!

**Comment by piermorel** [comment]
Nooo, the imgur link doesn't work!
I'll see how I can add that to the documentation, it's true that the example page is a bit long now. Maybe just mentioning copy() in the cheat sheet?

**Comment by MooMinIL** [comment]
imgur link is updated =]
I was originally thinking about simply mentioning simple actions like copy() in the cheatsheet but having remembered that it took me a while to get a grasp of how to use the cheatsheet and gramm in general, I think that a short intro of the steps required to make a gramm would actually help a great deal.

**Comment by piermorel** [comment]
Kind of an extended version of the "workflow" section in the realm page (main page on GitHub)?

**Comment by MooMinIL** [comment]
Something like that.
To be honest I only just now noticed that there's a "Workflow" section in the read! But well, that might just show that it should be available on either the cheatsheet or examples as well.
Also, I think a brief paragraph explaining how gramm works (i.e. gramm creates a MATLAB object containing the data for x,y axis grouping and other attributes, and then you can use this object's subroutines to choose how to display that data) might be in order, as the gramm code works quite differently from what MATLAB users are used to.

**Comment by piermorel** [comment]
Hi, good point about gramm not being "standard" Matlab, and explanation might also help on this.

If you have time to help on this that would be great! Maybe by submitting some more explanations to the first section of the examples.m file or the readme.md file, which then I could include at the beginning of the cheat sheet (the original document is a .numbers table that is not on github). I'd have to find a way to refer to the color coding that is used in the cheat sheet (which I need to improve).

**Comment by piermorel** [comment]
Hi, another gramm user opened a issue specifically for discussing tutorials/help, you can join the discussion if still interested: https://github.com/piermorel/gramm/issues/31
