### ISSUE TITLE
Computing ci intervals using a custom function

### ISSUE THREAD

**Issue by mnarayan** [piermorel/gramm#25]
For many types of data (e.g. with dependent or multi-level observations) standard methods of computing CI can be overoptimistic. It would be nice to be able to pass a function handle to `stat_summary()` to compute ci's more accurately in these cases. 

Perhaps one option could be to pass a custom `my_computeci` function as an alternative to the calls to `computeci` 
https://github.com/piermorel/gramm/blob/master/@gramm/stat_summary.m#L332
https://github.com/piermorel/gramm/blob/master/@gramm/stat_summary.m#L234

**Comment by piermorel** [comment]
Hi, thanks for the feedback :) On twitter I understood that you wanted to provide your own function to bootci() (for now it's mean, but median or other stuff might be interesting), which was trivial to do.

Your suggestion is way more interesting, and is probably not too complicated to do either, as it is doable by passing anonymous function(s), I'll see about it.

Another possibility, if you have nice CI functions that might be interesting to others, is to add them to my_computeci and submit a patch :) I'm pretty curious about multi-level observations, as it is true that gramm doesn't do stats depending on the number of groups or on their hierarchy and thus is overoptimistic (the only adjustment being the alpha level in set_stat_options() )

**Comment by mnarayan** [comment]
@piermorel Yes originally I was thinking of this as wanting a custom bootstrap function for similar reasons (I almost always compute ci's with bootstraps), but once I looked at the `stat_summary()` implementation as you suggested, this seemed a more handy/general solution.

**Comment by piermorel** [comment]
Yep, great idea, I'll add it soon.

There is a limitation to keep in mind though, about my previous point: one of the reasons that gramm doesn't do fancier statistics is that each geom_ or stat_ call is done completely independently for each smallest subgroup of the data. As a consequence the functions within don't know about the rest of the data. Workarounds would be possible but a lot of work to add (a kind of "pre-pass" system, tough to "open" to the user). Ultimately I also don't want to maintain a stats package... too much responsibility 😄

**Comment by mnarayan** [comment]
Yes good points. I can see how this gets complicated very quickly. I was
not at all thinking of this as a make it accurate across all groups and
such. Those would require knowing about the existence of other groups.

I would think though that as long as we're doing these on a per column of
data for the smallest group basis, the customization should work remain
compatible with stat_call.

Let me think of some `my_computeci` examples that should still be
elementary enough to not complicate things.

**Comment by piermorel** [comment]
I just added the functionality with the latest commit, here is sample code until I document it. Basically you just provide a function that takes y values (as an n_repetitions x n_data_points matrix) and returns both the central value and the CI with a matrix [y_mean ; yc_CI_low ; y_CI_high] (with y_mean, and y_CIs being 1 x n_data_points arrays). Let me know if that works for you!


```Matlab
%% Test stat_summary with custom function

x=repmat(1:10,1,30);
y=x*0.5;
y=y+randn(size(y));

figure
g=gramm('x',x,'y',y)
g.geom_point()
g.stat_summary('type',@(x)[nanmean(x) ; bootci(1000,{@(ty)nanmean(ty),x},'alpha',0.01)])
g.draw()


x=repmat(1:10,30,1);
y=sin(x/2)*4;
y=y+randn(size(y));

figure
g=gramm('x',x,'y',y)
g.geom_line('alpha',0.1)
g.stat_summary('type',@(x)[nanmean(x) ; bootci(1000,{@(ty)nanmean(ty),x},'alpha',0.01)])
g.draw()
```

**Comment by mnarayan** [comment]
This is awesome, thanks!  Here is a `trimmean` example which is something `stat_summary()` doesn't offer as an option.  I will follow up using some custom resampling methods that can't be done with matlab's `bootci`. 

```MATLAB
x = [1:10] + rand(1,10);
mu = 1.5*x;
y  = bsxfun(@plus,mu,trnd(2,[25 length(mu)]));

custom_statfun = @(y)([trimmean(y,2.5);bootci(100,{@(ty)trimmean(ty,2.5),y},'alpha',0.05)]); 

figure
g=gramm('x',x,'y',y)
g.geom_point()
g.stat_summary('type', custom_statfun)
g.draw()
```

**Comment by piermorel** [comment]
I documented the new functionality of stat_summary() using your example.
