### ISSUE TITLE
Plot limits for histograms?

### ISSUE THREAD

**Issue by MooMinIL** [piermorel/gramm#26]
Hey again,
I've been wondering if @piermorel (or anyone else reading this) might have an idea how to implement what I want to do using gramm:
I have a need to plot multiple histograms, of differing subsets and I've found that the configuration for "Superimposition of gramm objects on the same axes" suggested in the examples page works best for me.
So far I've managed to manipulate the code to suit my needs (I only use the top part of the gramm, with the subplots) but I'm still missing a method of plotting the spec limits for my distribution (as shown [here](http://imgur.com/a/sDqkj) by the vertical red lines).

When using just one gramm plot (and not a facet grid) I usually just add a line() plot from matlab according to the axis (and resize the gramm's axis, if the limits are out of bounds) but this is more difficult to achieve for a facet grid plot as it is hard to figure out which axis is the relevant one for each plot.

I thought about using a second gramm for the lines themselves but I couldn't figure out if it would work  as an overlay or not.

Any tips?

**Comment by piermorel** [comment]
I'm not 100% sure I understand what you want to achieve, but for additional annotating lines, the "proper" gramm way is geom_vline() in the case of vertical lines. This will plot the same lines in all facets. 

Plotting different lines on different facets will be a bit more hack-ish and require the use of update(). By trying to do it I realized that it's not extremely straightforward but is actually pretty flexible (you could have lies with different colors, etc. Let me know if that's what you are looking for!

```Matlab
%Generate fake data
cat_color = repmat([1 2 1 2],1,200);
cat_column = repmat([1 1 2 2],1,200);
x = cat_color + randn(size(cat_color)) + cat_column * 10;


%Gramm for the histogram
g=gramm('x',x,'color',cat_color)
g.facet_grid([],cat_column,'scale','free_x')
g.stat_bin('geom','overlaid_bar')
g.draw()

%Extract current state of the plots
temp_ylim=get(g.facet_axes_handles,'YLim');
temp_xlim=get(g.facet_axes_handles,'XLim');

%Generate data for the annotating lines
annot_x = [ 9 9 ; 14 14 ; 19 19 ; 24 24]
annot_y = repmat(temp_ylim{1},4,1)
annot_cat_column = [1 1 2 2];

%Use update() to provide the new data, and plot the lines, with additional options to make them look nice
g.update('x',annot_x,'y',annot_y,'color',[])
g.facet_grid([],annot_cat_column,'scale','free_x')
g.geom_line()
g.set_color_options('chroma',0)
g.set_line_options('styles',{'--' '-'})
g.draw()

%Restore the axes limits as they were after the first draw() call. Note
%that it's important to still have 'free_x' in the second facet_grid to
%prevent linking of the axes properties
set(g.facet_axes_handles,{'YLim'},temp_ylim);
set(g.facet_axes_handles',{'XLim'},temp_xlim);
```

![capture d ecran 2017-03-06 a 16 05 40](https://cloud.githubusercontent.com/assets/386604/23615476/d59a7cec-0286-11e7-9006-5181e85b9145.png)

**Comment by MooMinIL** [comment]
Hey! Sorry for taking a while to reply, this is definitely what I was looking for, I think that the update() function is somewhat under explored in the documentation/examples as I have yet to truly figure out what is it's extent.
For example I didn't realize I could update the plot with completely new 'x' and 'y' coordinates!
In any case, Thanks again for the assistance, it is very much appreciated.

**Comment by piermorel** [comment]
> I think that the update() function is somewhat under explored in the documentation/examples as I have yet to truly figure out what is it's extent.
Well we created the issue about documentation for that purpose :) The example above might end up in examples.m !
