### ISSUE TITLE
Editing the ylabel in plots generated with stat_bin

### ISSUE THREAD

**Issue by lachristos** [piermorel/gramm#29]
Hello,

thank you for this great toolbox!

Is there a way to alter the y label in histograms? For example if I use the defaults in stat_bin it reads 'count'. Is it possible to change this? I would expect it to be possible by calling set_names('y','mylabelhere') but it does not seem to be the case.

**Comment by piermorel** [comment]
Hi and thanks :)

You're right, it seems that stat_bin() overrides the name set with set_names(). I'll change it so that it says "count" only if the y name was unspecified.

**Comment by lachristos** [comment]
that was fast :) 
thanks again!

**Comment by piermorel** [comment]
Just pushed the commit now :)
