### ISSUE TITLE
Support Categorical Variables

### ISSUE THREAD

**Issue by iandol** [piermorel/gramm#3]
Hi, since MATLAB 2013b, there has been support for `table` and `categorical`, which provides a much richer way to organise statistical data for analysis. Ideally, gramm would be built around tables, but that would break backwards compatibility. Neverthless, it would be good to add support for at least categorical variables for the grouping variables. It almost works but breaks on line 1297:

```matlab
text(2.5,ind_scale,num2str(uni_color{ind_color}),'Interpreter','none')
```

It is easy to fix, but there are other places where the assumption of double OR cell is made.

**Comment by piermorel** [comment]
I now convert all categorical variables to cellstr internally, it should work. Using tables inside would make my life easier, but I thought they appeared much later, was the full functionality already there in 2013b ?

**Comment by iandol** [comment]
Thanks! Yes, according to `doc table` 2013b was when they were introduced. Thanks for the very fast fixes, and an already very useful tool (that can only get better)!
