### ISSUE TITLE
Pre-2014b versions

### ISSUE THREAD

**Issue by romainligneul** [piermorel/gramm#32]
Hi Pierre,

The lack of transparency on pre-2014b version is a bit annoying for people like me who use such versions.

I've just figured out that removing lines 1241-1248 (which sets the renderer to 'Painters') and adding the following statement at the top of the draw function (e.g line 28) works pretty well for me:

```
if verLessThan('matlab','8.4')
    warning('Pre-2014b version detected, forcing OpenGL to operate in software mode')    
    opengl software
end
```

Best,

Romain

**Comment by piermorel** [comment]
Hi Romain, glad to see you using gramm :)

Great find! The openGL renderer was causing bugs with bar plots under Windows for stat_bin() and switching to 'painters' was the only way I found to stop it at the time. I'll add your change in the next update and make a few other pre 2014b colleagues happy.

**Comment by piermorel** [comment]
Oh wait, on the Mac, there is no software openGL so the bug where axes lines are not rendered remains. I'll probably need an hybrid solution.

**Comment by romainligneul** [comment]
Sorry to hear that only Windows users will enjoy transparency again :).

Anyway, great piece of software!

**Comment by piermorel** [comment]
Hybrid solution added in the last commit... Windows-old-matlab-users will enjoy transparency again!
