### ISSUE TITLE
facet_grid documentation small mistake

### ISSUE THREAD

**Issue by behinger** [piermorel/gramm#36]
>    'scale' can be set to either 'fixed', 'free_x',
>     'free_y', **'free'**, or 'independent' so that the scale of the subplots is respectively
>      the same over all subplots, x adjusted per columns of subplots ,
>      y adjusted per rows of subplots, **x adjusted per rows and y per columns**,
>      or x and y adjusted independently per subplot

(Unfortunately for me ;-) ) This should be the other way round. See the code of `draw.m`
```matlab
case 'free'
                        temp_xscale='per_column';
                        temp_yscale='per_row';
```

**Comment by piermorel** [comment]
Good catch!
As for your "unfortunately", isn't 'independent' good enough?

**Comment by behinger** [comment]
I would like to have the same y_axis for each column.

As I understand:
free_x -> the y-axes of all panels are equal
free_y -> the x-axes of all panels are equal
free    -> the xscales are per column, the y-scales per row
independent -> all scales are free

what I need:
XXX -> the xscales are per row, the y-scales per column (thus the reverse of "free").

I think this is also not possible in ggplot2, but in my special case, I want to compare over columns (I could of course flip the whole plot, i.e. swap rows and cols und use "free", but thats not really an option for me.)

But it is really not important, I just wanted to point out the mixup in the documentation

**Comment by piermorel** [comment]
Documentation is corrected. For the rest, you could try to modify gramm to add the options? It's not an easy part of the code though.
