### ISSUE TITLE
set_continuous_color with multiple figures

### ISSUE THREAD

**Issue by behinger** [piermorel/gramm#37]
First of all, as always: Great work, this tool is invaluable!

If I run this script:
```matlab

figure
g = gramm('x',1:20,'y',1:20,'color',[ones(1,10) 1:10 ])
geom_line(g)

facet_grid(g,[ones(1,10),2*ones(1,10)],[])
fig(g,[1 1 1 2*ones(1,10-3),3*ones(1,10)])
set_continuous_color(g)
draw(g)
```

I get the error

```
Error using matlab.graphics.axis.Axes/set
While setting property 'CLim' of class 'Axes':
Value must be a 1x2 vector of numeric type in which the second element is larger than the first and may be Inf

Error in caxis (line 80)
            set(ax,'CLim',arg);

Error in gramm/draw (line 726)
            caxis([mi ma]);

Error in gramm/draw (line 125)
        obj{ind_fig}.draw();
 
80              set(ax,'CLim',arg);
```

In Line 726 and 885 (after you fix L726)

Because I have a figure where the color limit is [1,1] and matlab does not like this. Please note that the first error does not occur if the limit is [0,0] (i.e. `caxis([0,0])` works), but then the error at 885 still persists.

My current workaround:

 replace in draw.m Line 885 and Line 726
```matlab
        mi = min(min(obj.plot_lim.minc));
        ma = max(max(obj.plot_lim.maxc));
          
        if mi ~= ma
            caxis([mi ma]); % in L726
            set(ca,'CLimMode','manual','CLim',[mi ma]); % in L885
        end
```

But then I still get the not-useful colorbar legend. But it works :)

More general: I think the problem is, that set_continuous_color is defined for all figures, but should be defined for a single figure, or the obj.plot_lim.minc/maxc should either be over figures, or have default 0,0.

**Comment by piermorel** [comment]
Thanks for the detailed report, issue #34 recently was also related to color limits, I'll look into that.

**Comment by piermorel** [comment]
That's corrected in the last commit, along with the possibility to set 'CLim' in set_continuous_color(), which should make your color legends in multiple figures much better!

```Matlab
figure
g = gramm('x',1:20,'y',1:20,'color',[ones(1,10) 1:10 ])
geom_line(g)

facet_grid(g,[ones(1,10),2*ones(1,10)],[])
fig(g,[1 1 1 2*ones(1,10-3),3*ones(1,10)])
set_continuous_color(g,'CLim',[1 10])
draw(g)
```
