### ISSUE TITLE
update & geom_vline error

### ISSUE THREAD

**Issue by behinger** [piermorel/gramm#39]
If I want to plot another vline after updating, it throws an error

```matlab
figure
g = gramm('x',rand(20,20),'y',rand(20,20)')
geom_line(g)
geom_vline(g,'xintercept',0)
draw(g)

update(g)
geom_vline(g,'xintercept',1)
draw(g)
```

Results in error
```
Reference to non-existent field 'slope'.

Error in fill_abline (line 5)
ab.slope(end+1:end+l)=shiftdim(varargin{1});

Error in gramm/geom_vline (line 14)
    obj(obj_ind).abline=fill_abline(obj(obj_ind).abline,NaN,NaN,p.Results.xintercept,NaN,@(x)x,p.Results.style,p.Results.extent); 
```

The furthest I succeded with debugging: The field "abline" of ```obj(obj_ind)`` in geom_vline.m L14
is missing for the updated gramm object but not the original one (there it is empty, and a bunch of others as well). Hope that helps already.

**Comment by piermorel** [comment]
To be honest, I think this problem was there before the update! Latest commit fixed it, update() didn't reinitialize the Xline() parameters properly.
