### ISSUE TITLE
Support Simple Boxplots

### ISSUE THREAD

**Issue by iandol** [piermorel/gramm#4]
If I only have x (group) and y(value) data, stat_boxplot does not work:

```matlab
g=gramm('x',randi([1 2],50,1),'y',rand(50,1));
g.stat_boxplot();
g.draw
```

It should still generate a simple boxplot in this case, but the figure is blank.

**Comment by piermorel** [comment]
I spent too much time testing box plots with different colors and didn't check if it worked when there was none... fixed now (as well as incorrect whisker length) !
