### ISSUE TITLE
Differently sized subplots

### ISSUE THREAD

**Issue by janawrosch** [piermorel/gramm#40]
First, I want to thank you for creating this incredibly useful toolbox. It is a huge improvement to MATLAB.

Second, I'd like to ask if there is a way to generate subplots of different sizes similar to the ones you'd get when using for example subplot(2,2,[2,4]) in base Matlab.

Thank you so much.
Best
Jana

**Comment by piermorel** [comment]
Hi Jana, thanks for the feedback.

As I'm sure you noticed, gramm takes full control over the window so you can't use Matlab's subplot. Thus the main supported ways to generate subplots are with facet_grid() and facet_wrap(), or using a matrix of separate gramm objects.

A lot of the figures in examples.m are generated using a matrix of gramm objects, but this only provides the option to separate the figure in equal parts. When the different objects use different faceting, this can generate differently sized subplots however (see for example the last row in the **Grouping options in gramm** section in examples.m).

When using a single gramm object with facet_grid and facet_wrap, there is a possibility to get subplots of different sizes according to the scale of the data with the ```'space'```argument (see the **Options for separating groups across subplots with facet_grid()** section in examples.m).

None of these two options allow full control though. However I just thought of one hack-ish way which seems to kind of work (the dynamic resizing currently gets broken by it) and is based on the possibility to set Uipanels as gramm figure parents. It's a bit more low-level than subplot but allows more control. Here is some example code below... let me know if that works for you ! I'll see if I can make the resizing work with in a future update.

```Matlab
f = figure('Position',[100 100 1200 800])

% Create the uipanels, the 'Position' property is what will allow to create different sizes (it works the same as the corresponding argument in subplot() )
p1 = uipanel('Position',[0 0 0.6 1],'Parent',f,'BackgroundColor',[1 1 1],'BorderType','none')
p2 = uipanel('Position',[0.6 0 0.4 0.5],'Parent',f,'BackgroundColor',[1 1 1],'BorderType','none')
p3 = uipanel('Position',[0.6 0.5 0.4 0.5],'Parent',f,'BackgroundColor',[1 1 1],'BorderType','none')

load example_data;

g=gramm('x',cars.Model_Year,'y',cars.MPG,'color',cars.Cylinders,'subset',cars.Cylinders~=3 & cars.Cylinders~=5);
g.facet_grid([],cars.Origin_Region);
g.geom_point();
g.stat_glm();
g.set_names('column','Origin','x','Year of production','y','Fuel economy (MPG)','color','# Cylinders');
g.set_title('Fuel economy of new cars between 1970 and 1982');
g2 = copy(g);
g3 = copy(g);
g.set_parent(p1);
g.draw();

g2.set_parent(p2)
g2.set_color_options('map','brewer1')
g2.draw()
g3.set_parent(p3)
g3.set_color_options('map','matlab')
g3.draw()
```

![capture d ecran 2017-06-15 a 17 36 31](https://user-images.githubusercontent.com/386604/27189301-4cd9c9c0-51f1-11e7-8a66-b292b29a1441.png)

**Comment by janawrosch** [comment]
Dear Pierre,

Thank you so much for your comprehensive and immediate response.
The work around with uipanels is perfect and works great.

Of course, you are the expert, but I even think it is easy enough and not too hack-ish to just use that instead of a “proper” implementation in your toolbox. I think included the example in the documentation would probably be sufficient for users that want to do this.

Thank you again for your help and so very much for sharing this toolbox, it is such a help!
Best
Jana



Von: Pierre Morel [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. Juni 2017 17:41
An: piermorel/gramm
Cc: Wrosch, Jana; Author
Betreff: Re: [piermorel/gramm] Differently sized subplots (#40)


Hi Jana, thanks for the feedback.

As I'm sure you noticed, gramm takes full control over the window so you can't use Matlab's subplot. Thus the main supported ways to generate subplots are with facet_grid() and facet_wrap(), or using a matrix of separate gramm objects.

A lot of the figures in examples.m are generated using a matrix of gramm objects, but this only provides the option to separate the figure in equal parts. When the different objects use different faceting, this can generate differently sized subplots however (see for example the last row in the Grouping options in gramm section in examples.m).

When using a single gramm object with facet_grid and facet_wrap, there is a possibility to get subplots of different sizes according to the scale of the data with the 'space'argument (see the Options for separating groups across subplots with facet_grid() section in examples.m).

None of these two options allow full control though. However I just thought of one hack-ish way which seems to kind of work (the dynamic resizing currently gets broken by it) and is based on the possibility to set Uipanels as gramm figure parents. It's a bit more low-level than subplot but allows more control. Here is some example code below... let me know if that works for you ! I'll see if I can make the resizing work with in a future update.

f = figure('Position',[100 100 1200 800])



% Create the uipanels, the 'Position' property is what will allow to create different sizes (it works the same as the corresponding argument in subplot() )

p1 = uipanel('Position',[0 0 0.6 1],'Parent',f,'BackgroundColor',[1 1 1],'BorderType','none')

p2 = uipanel('Position',[0.6 0 0.4 0.5],'Parent',f,'BackgroundColor',[1 1 1],'BorderType','none')

p3 = uipanel('Position',[0.6 0.5 0.4 0.5],'Parent',f,'BackgroundColor',[1 1 1],'BorderType','none')



load example_data;



g=gramm('x',cars.Model_Year,'y',cars.MPG,'color',cars.Cylinders,'subset',cars.Cylinders~=3 & cars.Cylinders~=5);

g.facet_grid([],cars.Origin_Region);

g.geom_point();

g.stat_glm();

g.set_names('column','Origin','x','Year of production','y','Fuel economy (MPG)','color','# Cylinders');

g.set_title('Fuel economy of new cars between 1970 and 1982');

g2 = copy(g);

g3 = copy(g);

g.set_parent(p1);

g.draw();



g2.set_parent(p2)

g2.set_color_options('map','brewer1')

g2.draw()

g3.set_parent(p3)

g3.set_color_options('map','matlab')

g3.draw()

[capture d ecran 2017-06-15 a 17 36 31]<https://user-images.githubusercontent.com/386604/27189301-4cd9c9c0-51f1-11e7-8a66-b292b29a1441.png>
