### ISSUE TITLE
>15 colors in stat_density

### ISSUE THREAD

**Issue by janawrosch** [piermorel/gramm#41]
Sorry, to trouble you again, but there seems to be a problem with the colors when using more than 15 grouping items in a stat_density plot.

This is from the gramm examples but changed from geom_line to stat_density and doesn't work anymore. 

_load spectra.mat

%Here we create x as a 1xN array (see example above), and use a MxN matrix
%for y. Color applies to the M rows of y.
g18=gramm('x',900:2:1700,'y',NIR,'color',octane);
g18.set_names('x','Wavelength (nm)','y','NIR','color','Octane');
g18.set_continuous_color('colormap','hot');
g18.stat_density;
figure('Position',[100 100 800 450]);
g18.draw();_

Is there something I can do to make it work?
Thank you so much!

**Comment by piermorel** [comment]
Gramm automatically switches from discrete color groups to a  continuous color scale when there are more than 15 unique numerical values in 'color'... And only geom_line() and geom_point() can support continuous colors as all other geom_ and stat_ assume discrete categories. With the latest update (done right now) this behavior can now be overridden by calling ```g.set_continuous_color('active',false)```. Before the update it was possible to cheat using ```g18=gramm('x',900:2:1700,'y',NIR,'color',categorical(octane));```

Can you now do what you wanted?

Also the data in spectra is particularly not adapted to stat_density :)

**Comment by janawrosch** [comment]
g.set_continuous_color('active',false) works perfectly with the updated files!
