### ISSUE TITLE
Interpreter for labels and title

### ISSUE THREAD

**Issue by galli-a** [piermorel/gramm#42]
Would it be possible to change the interpreter of the labels and titles to 'Latex' or 'Tex'? This way we could also have subscript, superscript, and other LaTeX symbols

**Comment by piermorel** [comment]
gramm has a set_text_options() method, and it's possible to set the interpreter with it (it can also be used to change the sizes and font). Detailed help is available both in the documentation of the function and the cheat sheet. Let me know if it doesn't work as it should though !

**Comment by bwbj** [comment]
although the set_text_options() method is not as convenient / intuitive as set_names() for axis label.
