### ISSUE TITLE
how to set_order_options for facet_grid?

### ISSUE THREAD

**Issue by janawrosch** [piermorel/gramm#43]
The gramm_examples show how to change the order of e.g. bars with the line
set_order_options('x', {x_label_order})
This works perfectly for ordering x-values, color and lightness.

But with what do I replace the 'x' if I want to change the order of subplots in a facet_grid?

Example:
    g(2,1)=gramm('x', data.x_values);
    g(2,1).facet_grid(data.condition,[]);
    g(2,1).stat_bin();
    g(2,1).set_order_options( __???____ , {condition_label_order});   
This produces little "subplots" of the data split up by the condition and they are currently in ascending order and I would like to have them in a given order.

It would be great if anyone could help me with that.
Thank you so much!!

**Comment by piermorel** [comment]
This is documented both in the function itself (```doc gramm``` then click on set_order_options), and in the cheat sheet pdf. Short answer: same as 'x', 'color', etc., the function also takes 'row' and 'column' name value pairs just for this :)

**Comment by janawrosch** [comment]
Ah, I see, sorry.
Thank you!

Von: Pierre Morel [mailto:notifications@github.com]
Gesendet: Montag, 3. Juli 2017 17:22
An: piermorel/gramm
Cc: Wrosch, Jana; Author
Betreff: Re: [piermorel/gramm] how to set_order_options for facet_grid? (#43)


This is documented both in the function itself (doc gramm then click on set_order_options), and in the cheat sheet pdf. Short answer: same as 'x', 'color', etc., the function also takes 'row' and 'column' name value pairs just for this :)
