### ISSUE TITLE
Continuous Color for less than 15 values

### ISSUE THREAD

**Issue by behinger** [piermorel/gramm#48]
When plotting less than 15 colors, but activating continuous colormode using `set_continuous_color`, gramm.draw() is overwriting this and deactivates it again.

The  line 207 in @gramm/draw.m:

```matlab
   %If we have too many numerical values for the color we
    %switch to continuous color
    if length(uni_color)>15 && ~iscellstr(uni_color) && (isnan(obj.continuous_color_options.active) || obj.continuous_color_options.active)
        obj.continuous_color_options.active = true;
    else
        obj.continuous_color_options.active = false;
    end

```
could be changed to a logical-or; something like this:

```matlab
~iscellstr(uni_color)  && ( length(uni_color)>15 || (isnan(obj.continuous_color_options.active) || obj.continuous_color_options.active))
```

I hope this does not introduce issues further down the line.

Thanks again for the very well functioning toolbox!

**Comment by piermorel** [comment]
Thanks for letting me know, I have the feeling I keep breaking and fixing that all the time!

**Comment by piermorel** [comment]
OK, it should now work in all cases (also forcing discrete colors for more than 15 numerical categories!).
