### ISSUE TITLE
Coord_flip + legend order

### ISSUE THREAD

**Issue by matthijscox** [piermorel/gramm#49]
Hi Pier,

I was using the coord_flip functionality with geom_bar (I use bar plots a lot, I know).
When inspecting my results I was slightly confused, but then I noticed the data and the legend are not in the same order anymore. 

It's a minor thing, but when presenting such plots, I'd like them to be as intuitive as possible. So I was wondering if there is a way to either mirror the coordinate system in X, or to flip the order of the legend items?

![image](https://user-images.githubusercontent.com/17245881/29112543-7b0651a6-7cee-11e7-9d3c-1465a6593329.png)

I now see that in the ggplot cheatsheet, the coord_flip actually does the transformation as I would expect (mirrored w.r.t. your output):
![image](https://user-images.githubusercontent.com/17245881/29112410-167f31ee-7cee-11e7-98d4-baa84756480b.png)

Code for later reference:
```
x=[ones(4,1);2*ones(4,1)];
y=[1:4, 1:4]';
c=x;
l=repmat({'smallest','small','big','biggest'}',2,1);
xc = arrayfun(@num2str,x,'unif',0);

clear g
g(1,1)=gramm('x',xc,'y',y,'color',c,'lightness',l);
g(1,1).geom_bar('dodge',1.5,'width',1.2);
g(1,2)=gramm('x',xc,'y',y,'color',c,'lightness',l);
g(1,2).geom_bar('dodge',1.5,'width',1.2);
g(1,2).coord_flip();

g.set_names('y','','x','');
g.set_order_options('lightness',0);
g.axe_property('YTick',[],'LineWidth',1,'YColor',[1 1 1])

figure('Position',[100 100 600 200]);
g.draw();
```

**Comment by matthijscox** [comment]
Pier, my apologies, I really should have viewed the code first. There seems to be a simple solution, since you use native Matlab axe properties to do the flipping.

I can use the following to accomplish this (instead of using the coord_flip):
`g.axe_property('CameraUpVector',[-1 0 0])`

![image](https://user-images.githubusercontent.com/17245881/29112996-05323d3a-7cf0-11e7-9e8b-40dd98807436.png)

**Comment by piermorel** [comment]
Using coord_flip() indeed uses axes properties in a simple way, **but also sets is_flipped to true**, which is important in draw() and redraw(), especially when facets are used (otherwise scales are incorrect). So by just using axe_property alone you might run in problems.

I had done it the current way to have the axis point "up", but indeed for categories it does make sense to go from top to bottom. 

I can quickly add an option to coord_flip in order to set the axis direction.
