### ISSUE TITLE
Label issue

### ISSUE THREAD

**Issue by diasgabriela** [piermorel/gramm#53]
Hi, I started to use gramm this week, so I am a quite noob :)
How can I move my label on the negative bars?

Thank you!
![image](https://user-images.githubusercontent.com/27743808/34154049-54b13c90-e49b-11e7-917d-f63aec575b27.png)

**Comment by piermorel** [comment]
Hi Gabriela,

This is not something that can be done directly within gramm labels, as they just pass the alignment option (```'VerticalAlignment','middle'```) without doing any processing on it. However it's important to know that after the ```draw()``` call, the gramm objects contains a ```results``` field which should contain all the handles for the graphic elements in the plot, properly grouped. So it's possible to correct in your case, even though it's a bit convoluted:

``` Matlab
for k = 1:length(g.results.geom_label_handle) %Loop over colors
    tmp_pos = get(g.results.geom_label_handle{k},'Position'); %Get label positions
    tmp_pos = vertcat(tmp_pos{:}); %cell to mat
    sel = tmp_pos(:,2) <0; %Select the negative values
    set([g.results.geom_label_handle{k}(sel)],'VerticalAlignment','top'); %Change the alignment for those
end
```
