### ISSUE TITLE
Problem with update()

### ISSUE THREAD

**Issue by tabedzki** [piermorel/gramm#55]
Hi,

First off, I think porting ggplot2 is a great thing and I can really see this being useful in the future. 

One issue I have is with the update command when I run this block of code
`g=gramm('x',Banded_random.Mat_Size,'y',Banded_random.Time,'color',Banded_random.Algorithm_type);
g.facet_grid([],Banded_random.Band_percentage);
g.geom_point
g.axe_property('XScale','log')
g.axe_property('YScale','log')
figure('Position',[100 100 800 400]);
g.draw();` 

everything works well and a plot shows up. However, if I close the figure and run g.draw() again, I get a warning

` >>g.draw()
Warning: Multiple draw() calls need update() calls 
> In gramm/draw (line 103) 
ans = 
  gramm with properties:
     legend_axe_handle: [1×1 Axes]
      title_axe_handle: []
    facet_axes_handles: [1×5 Axes]
               results: [1×1 struct] `

and then running g.update() I get
`>> g.update()
ans = 
  gramm with properties:
     legend_axe_handle: [1×1 Axes]
      title_axe_handle: []
    facet_axes_handles: [1×5 Axes]
               results: []`

which clears all my results. When I try replotting it after update I get

`Error using axes
Invalid axes handle
Error in gramm/draw (line 409)
        axes(obj.facet_axes_handles(ind_row,ind_column));`

 Do you know if I am inputting things incorrectly or if this is an actual bug with the code?

**Comment by piermorel** [comment]
Hi @tabedzki ,

Both ```draw()``` and ```update()``` are not designed to work once the figure window is closed. ```draw()``` is for the first draw call on the currently opened figure window (or opens one if needed), and only works once. ```update()``` is to add new plot elements on the same figure window so it shouldn't be closed.
Is there a particular reason you want to close the window and then open it again? You could just delay the ```draw()``` call, or another possibility is to make a copy of the object if you want to do multiple figure windows (look at examples.m).

**Comment by tabedzki** [comment]
I did not want to re run the previous commands to reopen the window. I am new to this and was hoping to be able to redraw the plot easily similar to the built-in Matlab functions replotting easily. Is there a way to do this or does the whole procedure need to be re-run every time?

**Comment by piermorel** [comment]
I'm still not sure I understand... the window opening and plotting only happens at the ```figure``` ```draw``` call (contrary to ggplot2): you can do everything before that without anything appearing on screen.
Apart from the copy() possibility ```g2 = copy(g);``` right before calling ```g.draw``` ...  If you just want to reopen a stored figure, you can save it as a .fig and reopen it?

**Comment by tabedzki** [comment]
I like to use matlab interactively (a mix of scripts and command line) to try and make sure the code works well before scaling up to the whole problem I want to solve. One thing I tend to do is graph the plots quickly in the console without really using the all the other features of plotting (i.e., no labels, headers, and the like). I was curious if there was a way to easily replot the data without having to initialize the g object with another `g=gramm()`.

**Comment by piermorel** [comment]
The gramm object changes itself quite a bit when draw() is called, and I don't have an easy solution in mind to revert it back to its state before draw, apart from using a copy as I described above. 

I use the Matlab editor a lot with "sections" (with ```%% ```) which make it easy to edit code interactively without running into that sort of problem. gramm calls apart from figure creation and ```draw()``` are cheap computationally speaking so I can just rerun the whole section as I make the graph progressively better and better.
