### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by trallard** [piermorel/gramm#56]
Even though the (quite simple) installation instructions work as they are, I feel these a bit a dry especially for people only getting familiar with Git(Hub) and or MATLAB, even though if these seems very straightforward or trivial.

Feel free to disagree with this

**Comment by piermorel** [comment]
I will add a few simple instructions for install (maybe where to click on GitHub and a link to Matlab's add to path documentation?).

**Comment by trallard** [comment]
Great!

**Comment by piermorel** [comment]
Added in latest commit https://github.com/piermorel/gramm/commit/f74c06deb4944d41509667a102f7cf9b162351eb
