### ISSUE TITLE
Testing suite implementation

### ISSUE THREAD

**Issue by trallard** [piermorel/gramm#57]
gramm seems well developed so far but I could not find any test for the package.

I might have missed something, but if I haven't, have you considered adding any?

**Comment by piermorel** [comment]
Thank you for the comment. Currently, ```examples.m``` acts as a sort of test suite: even if it's presented as an example, it goes through all methods of gramm, and often tests multiple options for each. Some of the examples are also specific test cases for edge possibilities (see dodging examples for ```stat_summary``` and ```stat_boxplot``` in examples.m). By running examples.m I can examine the graphical output and make sure that everything is working as it should (and most of that is visual so it's impossible to test in an automated way).  Should there be more than that ?

**Comment by cMadan** [comment]
It might be good to have a folder with an html file that has all of the outputted figures from the examples, so someone who's never used the toolbox can compare the output of `examples.m` with the expected output? (I assume this isn't identical to the panels shown in the README)

**Comment by piermorel** [comment]
@cMadan There actually is an html/ folder in the repository, which contains all the figures and an index.html page produced by using Matlab's publish function on examples.m. I update it every time it's necessary. The images of the README do come from this html folder, but the folder contains more images than the README as it's the full output of examples.m . I indicated this in the paper in the paragraph where I describe available documentation and help.

**Comment by trallard** [comment]
I have checked the examples in the html folder and they are great, but I am afraid that the README documentation section gest a bit lost. 
I suggest changing the `html/examples.html` for [html/examples.html](./html/examples.html) or better yet have the html output to actually generate a webpage on your gh-branch and add the link to it in your README, this way people can actually see the rendered html version in their web browsers

**Comment by piermorel** [comment]
I used htmlpreview.github.io in order to make the html/examples.html link visible in the browser. I also made the role of examples.m as test file more apparent in CONTRIBUTING.md in https://github.com/piermorel/gramm/commit/f74c06deb4944d41509667a102f7cf9b162351eb
