### ISSUE TITLE
Adding contributing guidelines

### ISSUE THREAD

**Issue by trallard** [piermorel/gramm#58]
It is always useful to have a CONTRIBUTING.md for those who use the package and want to raise issues or make improvements... or even help with currently opened issues. 

I've seen you've already had some contributions an PR but in my experience having these guidelines in place encourage community participation.

**Comment by piermorel** [comment]
Thank you, I will add such a file... are there standards or models for these?

**Comment by cMadan** [comment]
There are some standard ones, e.g., https://www.contributor-covenant.org

**Comment by piermorel** [comment]
Added a simple one in latest commit https://github.com/piermorel/gramm/commit/f74c06deb4944d41509667a102f7cf9b162351eb
