### ISSUE TITLE
Statement of need- add to readme 

### ISSUE THREAD

**Issue by trallard** [piermorel/gramm#59]
I think the summary of the [software paper](https://github.com/openjournals/joss-papers/blob/joss.00568/joss.00568/10.21105.joss.00568.pdf) makes an excellent point on why gramm is needed and how it offers a better visualization environment for MATLAB users. This could probably be incorporated to the gramm repository.

This could be in a paragraph in the Readme... something like **Why gramm?**

**Comment by piermorel** [comment]
Good suggestion, I added it in the latest commit https://github.com/piermorel/gramm/commit/f74c06deb4944d41509667a102f7cf9b162351eb
