### ISSUE TITLE
geom_line, group and stat_summary

### ISSUE THREAD

**Issue by behinger** [piermorel/gramm#6]
##### Goal in R
In ggplot2 one can do the following:
```
ggplot(data.frame(x=rep(1:10,5), y =rnorm(50),group=sort(rep(1:5,10))), aes(x=x,y=y,group=group)) +
geom_line() + 
stat_summary(aes(group=NA),color='red')
```
Resulting in:
![rplot](https://cloud.githubusercontent.com/assets/10183650/14522556/5b9bb3b4-022f-11e6-8401-ab589fcb8d50.png)

##### The same thing in matlab
The same thing in matlab:
```

        g = gramm('x',repmat(1:10,1,5), 'y',randn(50,1))%,'group',sort(repmat(1:5,1,10)));
        g.geom_line() 
        g.stat_summary()
        g.draw()
```

in gramm I don't think this is possible due to the missing `stat_summary(aes(group=NA))` option.
I'm either stuck with connected lines (if I drop the group=group statement from the initial call) like this:

![untitled](https://cloud.githubusercontent.com/assets/10183650/14522724/30875948-0230-11e6-9d5c-cb7ae52ca055.jpg)
(the CI - lines are very faint but there. I did not want to change the call further).

or the stat_summary function tries to calculate the CI in one group (exactly as it should!).

![untitled](https://cloud.githubusercontent.com/assets/10183650/14522691/0e731144-0230-11e6-9897-02e0661f53d6.jpg)

I guess this is a limitation of the current implementation and I don't see a simple solution to it. Nevertheless I thought to post this here, maybe it helps in further development!
I still enjoy using the tool very much, keep up the good work (and the cheatsheet is superb!).

**Comment by piermorel** [comment]
Hi, thanks for the feedback

This is indeed a limitation I'm well aware of: basically gramm only allows to set aesthetics (to take ggplot's terminology) in the constructor gramm(). Given the way it works it would be pretty hard currently to allow geom-specific aesthetics. For this particular problem however, there are two workarounds detailed below. Let me know if you have any questions !

The first one is not so elegant, but allows to superimpose two gramm objects on the same axes. Basically you make one gramm with the groups and the geom_line(), draw it (using false as argument for draw), and the do another gramm without the groups and with the stat_summary().
There is an example in examples.m:
```matlab
g10b=gramm('x',Horsepower,'y',Acceleration,'subset',Cylinders~=3 & Cylinders~=5)
g10b.stat_glm('geom','area','disp_fit',false)
g10b.set_color_options('chroma',0,'lightness',30)
g10b.draw(false)
g10=gramm('x',Horsepower,'y',Acceleration,'color',Cylinders,'subset',Cylinders~=3 & Cylinders~=5)
g10.set_names('color','# Cylinders','x','Horsepower','y','Acceleration')
g10.geom_point()
g10.draw();
```
![carbig_glm_example](https://cloud.githubusercontent.com/assets/386604/14536537/2f9f99ee-0273-11e6-86a7-5f602988d2f1.png)

The second way to do this, which is much more elegant if your data is set up properly, is to use gramm's abiliity to take x and y input as cells or matrices, and not only as 1D arrays like ggplot. This allows to do proper lines without providing a group, and stat_summary() behaves properly (and has a lot of options to deal with that). There is a portion of examples.m which describes this:

```matlab

%Standard ggplot-like input (arrays for everything)
Y=[1 2 3 4 5 2 3 4 5 6 3 4 5 6 7];
X=[1 2 3 4 5 0 1 2 3 4 -1 0 1 2 3];
C=[1 1 1 1 1 2 2 2 2 2 2 2 2 2 2];

%Note the continuous line connecting all blue data points, gramm can't know
%when to start a new line in this case
figure
g11=gramm('x',X,'y',Y,'color',C)
g11.geom_line()
g11.draw()

%Adding a group variable solves the problem in a ggplot-like way
G=[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3];
figure
g12=gramm('x',X,'y',Y,'color',C,'group',G)
g12.geom_line()
g12.draw()

%For a more matlab-like solution, Y and X can be matrices, rows will automatically be considered as groups.
% as a consequence grouping data (color, etc...) are provided for the rows !
Y=[1 2 3 4 5;2 3 4 5 6; 3 4 5 6 7];
X=[1 2 3 4 5; 0 1 2 3 4; -1 0 1 2 3];
C=[1 2 2];
figure
g13=gramm('x',X,'y',Y,'color',C)
g13.geom_line()
g13.draw()

% If all X values are the same, it's possible to provide X as a single row
X=[1 2 3 4 5];
figure
g14=gramm('x',X,'y',Y,'color',C)
g14.geom_line()
g14.draw()

%Similar results can be obtained with cells of arrays
Y={[1 2 3 4 5] [2 3 4 5 6] [3 4 5 6 7]}
X={[1 2 3 4 5] [0 1 2 3 4] [-1 0 1 2 3]}
figure
g15=gramm('x',X,'y',Y,'color',C)
g15.geom_line()
g15.draw()

Y={[1 2 3 4 5] [2 3 4 5 6] [3 4 5 6 7]}
X=[1 2 3 4 5];
figure
g16=gramm('x',X,'y',Y,'color',C)
g16.geom_line()
g16.draw()

%With cells of arrays, there is the opportinity to have different lengths
%for different groups
Y={[1 2 3 4 5] [3 4 5] [3 4 5 6 7]}
X={[1 2 3 4 5] [1 2 3] [-1 0 1 2 3]}
figure
g17=gramm('x',X,'y',Y,'color',C)
g17.geom_line()
g17.draw()
```

**Comment by behinger** [comment]
Thanks for your response.
I tried the second solution, but ran into problems with using facet at the same time.
```
Y={[1 2 3 4 5] [3 4 5] [3 4 5 6 7]}
X={[1 2 3 4 5] [1 2 3] [-1 0 1 2 3]}
Z={[1 1 1 2 2],[1 1 2],[1 1 2 2 1]}
figure
g17=gramm('x',X,'y',Y,'color',C)
g17.facet_grid(Z,[])
g17.geom_line()
g17.draw()
```
```
Error using cell/unique (line 85)
Input A must be a cell array of strings.

Error in gramm>unique_and_sort (line 4231)
    y = unique(x,'stable'); %we keep the original order

Error in gramm/draw (line 1086)
            uni_row=unique_and_sort(temp_row_facet,obj.order_options.row);
```
A third option is to calculate the summary statistics before and manually concatenate it. 
But I'm now using the first option.

I also found a nice feature, that might be included in the cheatsheet.
In order to get transparency for lines one can do this:
```
g.set_color_options('map',[1.0000    0.3673    0.4132 0.05])
```
this basically sets `color(4) = 0.05`. See also here:
http://undocumentedmatlab.com/blog/plot-line-transparency-and-color-gradient


In any case, I'm very happy. Thank you again.

**Comment by piermorel** [comment]
With the second solution, the only inputs that can be 2D arrays/cells are X and Y. All the others (color, facets...) are 1D arrays/cellstr of size n_rows if X/Y are matrices or n_cells if X/Y are cells. In the examples I give and the one you tried, only an input of length 3 would work. Indeed X and Y have 3 elements, the rows or arrays of X/Y are not separable.

This functionality was created to easily plot repeated trajectories/time varying signals in different conditions. Since you seem to be a fellow neuroscientist, think of Y as your even-aligned EEG traces for your whole dataset (1 trace per trial, Y given as an N_trials x N_samples matrix). X would just be time (1:n_samples)/sampling_frequency. Then all other variables have a single value per trial ( e.g. 'color' would be trial condition, facet would be different subjects IDs, etc.). If you use stat_summary() you can get your ERPs directly !

Thanks for the tip about transparency, I'll check it out !

**Comment by behinger** [comment]
I see and understand way better. Thanks again!

**Comment by piermorel** [comment]
Hi, just wanted to warn you that I changed the unsatisfactory way things were working for that problem. Things are now way more flexible, and the number of facets can even be changed. See the "Using different groups for different stat_ and geom_ methods by superimposing gramm plots" section in examples.m

**Comment by rvenegas2014** [comment]
Mahalo Pierre, will run matlab tomorrow when get to my office.
