### ISSUE TITLE
Questions on the use of gramm - iosr.statistics.boxPl function

### ISSUE THREAD

**Issue by rvenegas2014** [piermorel/gramm#63]
This as a great tool, Mahalo for creating and sharing this with us!

I apologize in advance if any of my questions have already an answer (if so, please direct me to those answers). 

1)	Is it possible to modify the position of the 'sampleSize' on the figure to skip overlapping when having multiple boxes (e.g. rotate it, have an individual legend (color = value) within each section of a figure, have a reference box as part of legend, or shift position between top and bottom of consecutive boxes?

2)	Would be possible to change the ‘boxcolor’ colormap to comply with perception-deficiencies (colorblind, as now required for publications and federal documents)? I tried @gray and works fine, but including other colormap-for-colorblind people would be appreciated.
Like colormap(ametrine(256,'gamma',1.8,'minColor','black','maxColor',[0 1 0]));
from:https://www.mathworks.com/matlabcentral/fileexchange/31761-colormaps-compatible-with-red-green-color-perception-deficiencies

3)	Could be possible to modify individually the text format and size of a particular portion of the figure?

4)    Could be possible to add a NaN to places where no data exist? 

5)    How to manually modify YLim? When creating multiple figures you may want to have the same YLim for all/some of them. I am using g=iosr.statistics.boxPlot(...)  then g.axe_property('YLim',[10 40]);
The error I get is: No appropriate method, property, or field 'axe_property' for
class 'iosr.statistics.boxPlot'. 

6) How to add a horizontal reference line on the figure created by iosr.statistics.boxPlot(...) ?

This is what I am working on: 
![colorfigure](https://user-images.githubusercontent.com/9973980/37319992-b1eab70e-2615-11e8-92fd-06eee97e73cb.png)

Mahalo!

**Comment by piermorel** [comment]
Hi @rvenegas2014 ,

```iosr.statistics.boxPlot``` is **not** a gramm function so I really can't help you with that. Use the ```stat_boxplot()``` in gramm to get boxplot functionality. If you switch fully to gramm the answer is yes to almost all your questions: look in examples.m, its [output](http://htmlpreview.github.io/?https://github.com/piermorel/gramm/blob/master/html/examples.html) and the cheat sheet on how to do things !

Once you have working gramm-only code and still have questions, you are welcome to reopen the issue.

**Comment by rvenegas2014** [comment]
Thank you so much for your email, and clarification.

I apologize for my mistake. I will spend time on gramm in the next few
weeks as I found this a very useful tool for what we are working on.

Mahalo,
R.
