### ISSUE TITLE
Adding custom properties

### ISSUE THREAD

**Issue by anne-urai** [piermorel/gramm#67]
Is it possible to define custom gramm properties, for example in a startup script? I use a few specific calls to gramm that are too long to remember and a bit cumbersome to copy-paste, e.g. 

g.stat_fit('fun', @(a,b,g,l,x) g+(1-g-l) * (1./(1+exp(- ( a + b.*x )))), ...
    'StartPoint', [0 0.1 0.1 0.1], 'geom', 'line', 'disp_fit', false, 'fullrange', false);
could be shortened to e.g. g.custom_psychometric()

What would be your recommended way of doing this?
Thanks for a great toolbox!

**Comment by piermorel** [comment]
Hi Anne,

Given the way Matlab's object oriented programming works I'm not sure it would work exactly the way you want (the method would need to be declared in gramm.m). But It should be OK to create a function or anonymous function that can rather be called this way ```custom_psychometric(g)```.

Have you tried something like that ?
```Matlab
custom_psychometric = @(gramm_obj) gramm_obj.stat_fit('fun', @(a,b,g,l,x) g+(1-g-l) * (1./(1+exp(- ( a + b.*x )))),...
'StartPoint', [0 0.1 0.1 0.1], 'geom', 'line', 'disp_fit', false, 'fullrange', false);

custom_psychometric(g)
```

**Comment by anne-urai** [comment]
That works great, thanks!
