### ISSUE TITLE
access to low-level handles

### ISSUE THREAD

**Issue by anne-urai** [piermorel/gramm#68]
Is it possible to access the low-level plot handles after generating a gramm object? I'd like to change e.g. the markersize in a geom_point object. I fully understand that adding each and every attribute is impossible - so is there an easy way for the user to enforce such plotting details?

**Comment by piermorel** [comment]
Hi Anne,

Sure you can access them after issuing the draw() command through the ```gramm_object.results```structure, which should contain everything in a tidy way. There are also the axes handles accessible through the gramm object. You can find examples here : https://htmlpreview.github.io/?https://github.com/piermorel/gramm/blob/master/html/examples.html#38
