### ISSUE TITLE
stat_bin() overlaid_bar transparency level

### ISSUE THREAD

**Issue by dag618** [piermorel/gramm#69]
There doesn't seem to be a way to change the alpha/transparency level for either stat_bin or geom_bar.

**Comment by piermorel** [comment]
`stat_bin()` has a `'fill','transparent'` option but the alpha level is fixed. For both `stat_bin()`and `geom_bar()` you can set transparency after the draw call is issued by using `set()` and the handles as described here https://github.com/piermorel/gramm/issues/68
