### ISSUE TITLE
data sequence in stat_bin() or stat_boxplot()

### ISSUE THREAD

**Issue by Zousiyu** [piermorel/gramm#74]
hello! Gramm is a excellent toolbox for matlab, thank you very much.

There is a problem, it seems you sort the data in function which named stat_bin().

actually, the expected sequence is natural sequence, or respect to the original sequence. In here, it is [1000, 2000, 5000, 10000].

![image](https://user-images.githubusercontent.com/7608449/49137127-82966000-f326-11e8-95a0-4122a74edb16.png)

**Comment by piermorel** [comment]
Hi,

The sorting is alphabetical by default which explains your observation, but you can change the ordering options for different parameters using set_order_options(). There are examples in examples.m and the function is documented.
