### ISSUE TITLE
Marker color in geom_jitter

### ISSUE THREAD

**Issue by wildetudor** [piermorel/gramm#76]
How can I set the marker face color for the data points plotted by geom_jitter? 

There doesn't seem to be a 'color' or 'facecolor' property to this function's input arguments, and I didn't find any helpful examples to extrapolate from in the examples.m 

The only related code I found in the examples was the line 
`set([g.results.stat_glm.area_handle],'FaceColor',[0.4 0.4 0.4]);`
but it does not work if I replace the stat_glm layer with geom_jitter.

Thanks for any help! And apologies for the frugality of this seemingly basic question, but I am at my wit's end trying to figure this out by trial&error and from the documentation, and I have zero experience with classes or objects in programming.

**Comment by piermorel** [comment]
Hi Tudor,

If you want to set colors that are different from the default colors, you can use the gramm method ```set_color_options()``` to use different colormaps (see [examples.m](https://htmlpreview.github.io/?https://github.com/piermorel/gramm/blob/master/html/examples.html#32) ) This will have the advantage that you can still use a color grouping variable and is the recommended way to do things in gramm.

If you are in a case where you want to change colors "by hand", using set() after the final draw call is indeed the way to go. The handle to geom_jitter objects is in ```g.results.geom_jitter_handle```. These are line objects and the properties are described in [Matlab's help](https://fr.mathworks.com/help/matlab/ref/matlab.graphics.primitive.line-properties.html). You want ```MarkerFaceColor```.
