### ISSUE TITLE
Adjustable Legend

### ISSUE THREAD

**Issue by frarichter** [piermorel/gramm#8]
It would be really good if function would provide the option of moving the legend inside the plot to several position.

**Comment by piermorel** [comment]
In the latest commit there is a workaround that allows to place the legend anywhere on the figure once the draw() call is issued. There is sample code below. I'm leaving this issue open as a todo for more complete legend position customization.

```matlab
load example_data;
g=gramm('x',cars.Model_Year,'y',cars.MPG,'color',cars.Cylinders,'subset',cars.Cylinders~=3 & cars.Cylinders~=5);
g.facet_grid([],cars.Origin_Region);
g.geom_point();
g.stat_glm();
g.set_names('column','Origin','x','Year of production','y','Fuel economy (MPG)','color','# Cylinders');
g.set_title('Fuel economy of new cars between 1970 and 1982');
g.draw();

%The no_legend() call allows to remove the space on the left
g.no_legend()
legend_pos=get(g.legend_axe_handle,'Position');
%This places the legend at the desired location (coordinates in the whole figure).
set(g.legend_axe_handle,'Position',[0.74 0.25  legend_pos(3) legend_pos(4)]);
g.redraw()
```

![capture d ecran 2016-06-02 a 14 18 59](https://cloud.githubusercontent.com/assets/386604/15744588/155ebcb0-28cd-11e6-9144-d3873112fec8.png)

**Comment by ppxma7** [comment]
That's useful! 
I didn't think this warranted being a new issue, but I have a more tutorial/how to question, which I can't find the answer to in the documentation.
For the colorbar legend, let's say I have values that are from 0.000 to 5.000, with a range of possibilities in between, e.g 3.141, the colorbar numbers go a bit haywire, whereas, i'd just like to set some integer values? Sorry, silly question (newbie gramm user) - hope someone can help!
Thanks

![screen shot 2017-04-13 at 14 45 33](https://cloud.githubusercontent.com/assets/14826019/25007320/f5236c2e-2057-11e7-9ff6-5410387e64e6.png)

**Comment by piermorel** [comment]
Legend positions are fully customizable since the last commit. The limits of continuous color legends can be set using the 'CLim' argument in set_continuous_color().
