### ISSUE TITLE
Enable brushing of plots

### ISSUE THREAD

**Issue by OelDense** [piermorel/gramm#80]
Hi,

I'd like to brush and link data points between different plots.
However if I use for example  gplot.geom_point() I'm not able to brush data as the data points don't change their color.

**Comment by piermorel** [comment]
Hello,

I don't do anything in particular in gramm to prevent or allow data point brushing. However, given that you copy your data _into_ gramm (which uses it in a specific way for the plotting) I doubt you could meaningfully brush it and link it with data from outside of gramm. That said, I don't kow much about brushing as I don't use it.

**Comment by OelDense** [comment]
Thank you for the fast answer.
Brushing and linking data between plots does not work if the data points are saved in a structure  (Matlab Support).
