### ISSUE TITLE
grid lines in scatter/violin/bar plots?

### ISSUE THREAD

**Issue by danielemarinazzo** [piermorel/gramm#81]
Is it possible to have horizontal grid lines, helpful to evidence differences in mean/median etc when plotting several groups with violin plots?

thanks!

**Comment by piermorel** [comment]
Hi Daniele,

Sure it's possible to add them by modifying axes properties (as you would in a normal matlab figure). In gramm you access these properties in all facets by using ```gramm_object.axe_property('YGrid ' , 'on')```
You could also use geom_hline() for more customized placement.

I hope that helped!
