### ISSUE TITLE
Changing color of updated geom_line after density scatter plot

### ISSUE THREAD

**Issue by NigelCol** [piermorel/gramm#82]
Hi Pierre,

I wonder if it's possible to change to color of a line plotted with geom_line() independently of the color map used from a plotted densitity heat map. For example my dummy code looks like this,
g=gramm('x',x,'y',y)
g.stat_bin2d('geom','image')
annot_x=[0 1.5];
annot_y=[0 1.5];
annot_cat_column=[1 1];
g.update('x',annot_x,'y',annot_y,'color',annot_cat_column)
g.geom_line()
g.set_color_options('chroma',0,'lightness',0)
g.draw()

At the moment it does not change the color of the line to black as I thought it would using the set_color_options. I can only change the line to a color of the heatmap  by changing annot_cat_column to having different values (1,2,3). 

cheers,

Nigel

**Comment by piermorel** [comment]
Hi, sorry for the considerable delay.
For this use (annotation), you could try using `geom_polygon()` where you can easily control line color. Otherwise your example is not complete so it's hard to tell, you didn't issue a `draw()`call before `update()`.
