### ISSUE TITLE
Changing alpha of stat_boxplot

### ISSUE THREAD

**Issue by ppxma7** [piermorel/gramm#83]
Hi Pier

I have edited stat_boxplot a tiny bit to allow for a transparent box plot. I want to overlay data points, which works great using g.update() and geom_jitter.
I've added 3 new aesthetic parameters: alpha, linewidth and drawoutlier. I'm not super sure how to submit a push request, but let me know what you think?

Thanks
Michael
[stat_boxplot2.txt](https://github.com/piermorel/gramm/files/3034896/stat_boxplot2.txt)

**Comment by piermorel** [comment]
Hi Michael, thanks for the idea !

I actually don't want to provide too many graphic fine tuning parameters in gramm unless they are really time savers or implicate the inner working of gramm. For the good reason that it would never be the end of it !

I recommend doing these adjustments after the gramm call by using the handles of the graphic objects, for example like this for boxplot alpha a single line is enough:
`set([g.results.stat_boxplot.box_handle],'FaceAlpha',0.5);`
