### ISSUE TITLE
latex interpreter?

### ISSUE THREAD

**Issue by danielemarinazzo** [piermorel/gramm#89]
Hi Pierre, is the latex interpreter compatible with gramm? we're having an issue with using greek letters in the captions. thanks!

**Comment by piermorel** [comment]
Hi Daniele,

Matlab's ```'interpreter'``` options is available through gramm's ```set_text_options()```, which should fix this kind of thing. Let me know if that works as expected !

**Comment by danielemarinazzo** [comment]
Dear Pierre

the issue indeed came up when modifying tick labels, and we found that in draw.m, line 1115, where it says:

set(ca,'TickLabelInterpreter','none')

it should probably be saying:

set(ca,'TickLabelInterpreter',obj.text_options.interpreter)

otherwise the interpreter settings are overwritten.

d.

**Comment by zhangfan-space** [comment]
https://github.com/piermorel/gramm/issues/47
