### ISSUE TITLE
How to set the color of geom_raster?

### ISSUE THREAD

**Issue by Gery111** [piermorel/gramm#90]
hello,
I'm trying to use gramm to plot the firing of spike train, but I find the arguements are only geom"line" and geom "point". 
I want to show the data that every row has one  timestamp in other color, or  some row have one color, some row have another color, like this:
![批注 2019-12-16 120046](https://user-images.githubusercontent.com/46239634/70878307-e0fab300-1ffb-11ea-96fe-467a0fc544d2.png)
![批注 2019-12-16 120148](https://user-images.githubusercontent.com/46239634/70878308-e1934980-1ffb-11ea-92d4-a51e0e67869b.png)

Could I do this in Gramm?
Thank you

**Comment by Gery111** [comment]
And another request, can I set the transparentand the size of the point/line ?

**Comment by Gery111** [comment]
Using update can do this.

**Comment by piermorel** [comment]
Update should likely not be used for this : the whole point of gramm is that you can provide a grouping variable that will set the color automatically whatever the geom_ used. You just give a 'color' argument in the first gramm() call and you are good to go provided your trials are ordered. There is an example in examples.m

**Comment by Gery111** [comment]
@piermorel 
Hello, Piermorel, 
Yes, set gramm( "color", group variable) could set the color of different rows, but it looks cannot set different color in one row.
I am trying to use 
`gramm('x',spiketime1, 'color', group)
set_color_option(one color)
update('x', timestamp)
set_color_option(another color)`
and it works. I can make one row has two color of dots. Even I still do not know how to set one row that has more than two colors, because if I use update twice, the first call is missed.

**Comment by piermorel** [comment]
It seems that you reached the limit of what could be done within gramm unfortunately...
