### ISSUE TITLE
special charecters in axis don't show up

### ISSUE THREAD

**Issue by jorjio** [piermorel/gramm#91]
Hi,
I'm looking for a way to add greek/special characters in the axis - I'm using the option .set_names, and characters like /mu doesn't interpret to greek letters on the figure.

any ideas?
<img width="54" alt="MATLAB_2019-12-26_11-28-30" src="https://user-images.githubusercontent.com/5610394/71482881-e06bd480-27d2-11ea-8e59-eb3f96eaa66f.png">
thanks!

**Comment by piermorel** [comment]
Hi, sorry for the delay
Did you try setting the proper 'interpreter' using `set_text_options()`?

**Comment by jorjio** [comment]
I didn't notice this option - works just fine!
Thanks!
