### ISSUE TITLE
geom_funline ColorOrder based on Matlab not gramm

### ISSUE THREAD

**Issue by Josephine-Reuther** [piermorel/gramm#97]
geom_funline uses matlabs ColorOrder and therefore colors instead of gramm colors
Can this be changed or added as an option? 

I am currently using this to fix it "set(groot,'DefaultAxesColorOrder',[gramm's color values])" to add  lines that have the same colour as the associated data.

But I am sure there must be a better solution than that, is there?

**Comment by piermorel** [comment]
Hi @Josephine-Reuther ,

Sorry for the delay in answering. All these functions : `abline`, `hline`, `vline`, `funline` are for annotation that is independent of data (they are same for every subplot and don't use the date at all !) and thus do not follow Gramm's color order (you can set their color using the 'style' argument). If you want to add lines to graphs that follow the Gramm color order, I suggest using `update()`
