### ISSUE TITLE
 Compatibility with Matlab built-in figure system

### ISSUE THREAD

**Issue by Thundor404** [piermorel/gramm#98]
Hey,
The gramm is an excellent lib for me to export academic fig quickly. These several issues may improve its compatibility for old figure adjustment codes.
- set addition invisible axes _'HandlesVisible'_ as _'off'_ or return handles of target axes. In this version of gramm, all built-in order base on _'gca'_ will lose efficacy.  This problem troubled me for several hours.
- I wish a more consistent and powerful legend function can be added. The legend can not work for several superimposing gramm object to my knowlegement. And adjust its' positions is not convenient, considering that parameters such as _'southeast'_ can adjust the position easily in Matlab.

**Comment by piermorel** [comment]
Hi @Thundor404 

Thanks for the feedback, I hope this will answer your questions, I'm not sure I get everything that you mean :

- For all your axes customization needs, the gramm object contains all the generated handles as properties once `draw()` is called, you can find example code in the "advanced customization of gramm figures" in `examples.m`. Gramm uses gca() for backcompatibility.

- You can customize the legend position with `set_layout_options()` It's not as practical as 'southeast' from Matlab, but with all the tinkering that goes on behind the scenes to make gramm work (notably the auto resizing that keeps everything neat) it gets really hard to support the variety of what people wish do. So for now it's either automatic and the way it is or fully custom and manual with `set_layout_options()`. You are welcome to propose enhancements with a pull request.
